import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { gzipSync } from 'node:zlib';

const root = process.cwd();
const html = fs.readFileSync(path.join(root, 'dist/index.html'), 'utf8');
const canonical = 'https://www.pinnacleblooms.org/top-speech-therapy-center-india-proven-improvement-rate';
const checks = [];
function check(name, condition) { assert.ok(condition, name); checks.push(name); }
check('One persistent H1', [...html.matchAll(/<h1\b/g)].length === 1);
check('Preview remains noindex', /name="robots" content="noindex, nofollow"/.test(html));
check('Existing service canonical retained', html.includes('rel="canonical" href="'+canonical+'"'));
check('Nine explanatory cards are in initial HTML', [...html.matchAll(/class="stack-card /g)].length === 9);
check('All phone links use the international number', [...html.matchAll(/href="(tel:[^"]+)"/g)].every(m => m[1] === 'tel:+919100181181'));
check('No empty links', !/href="(?:#|)"/.test(html));
check('Dated service information linked', html.includes('href="/speech-therapy/service-information"'));
check('Confirmed assessment offer replaces conflicting price', html.includes('<del>₹25,999</del>') && html.includes('FREE') && !html.includes('Confirm the fee') && !html.includes('₹2,599'));
check('Service-fit and offer precede explanation', html.indexOf('id="assessment-start"') < html.indexOf('id="everyday-communication"'));
check('Official logos used', html.includes('Official Pinnacle logo') && html.includes('company emblem'));
check('Review changes the next decision',html.includes('Keep the goal. Adjust the practice.'));
check('Existing enrolment destination used', html.includes('href="https://www.pinnacleblooms.org/enroll"'));
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
check('Unique HTML IDs', new Set(ids).size === ids.length);
check('Every fragment link has a target', [...html.matchAll(/href="#([^"]+)"/g)].every(m => ids.includes(m[1])));
const graph = JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1])['@graph'];
const entities = new Map(graph.map(e => [e['@id'],e]));
const webpage = graph.find(e=>e['@type']==='WebPage');
const service = graph.find(e=>e['@type']==='Service');
check('WebPage points to Service', webpage.mainEntity['@id']===service['@id']);
check('Legal operator is the service provider', entities.get(service.provider['@id']).name==='Bharath Healthcare Laboratories Private Limited');
check('Pinnacle remains a separate Brand', entities.get(service.brand['@id'])['@type']==='Brand');
check('No invented ratings or clinical review', !graph.some(e=>e.aggregateRating||e.review||e.reviewedBy));
const assessment=graph.find(e=>e['@id']===canonical+'#assessment');
check('Free offer is scoped to assessment only', !service.offers && assessment.name==='Speech and language assessment' && assessment.offers.price===0 && assessment.offers.priceCurrency==='INR' && assessment.offers.itemOffered['@id']===assessment['@id'] && html.includes('Ongoing therapy is priced separately'));
check('Relevant clinical source is cited instead of count ledger', webpage.citation.includes('https://www.pinnacleblooms.org/question-comprehension-study') && !webpage.citation.includes('https://www.pinnacleblooms.org/verify/evidence/claim-ledger.html'));
check('Seven family pathway stages remain separate from technical walkthrough', [...html.matchAll(/class="care-number"/g)].length===7 && html.includes('not a separate nine-stage treatment programme'));
check('Actual enquiry destination used for every assessment CTA', [...html.matchAll(/<a[^>]+data-cta="(?:hero-assessment|mobile-assessment|visit-enquiry)"[^>]*>/g)].every(m=>m[0].includes('href="https://www.pinnacleblooms.org/enroll#contact-form-title"')));
check('Worked example is visible without opening technical content',html.indexOf('class="worked-example"')<html.indexOf('class="technical-walkthrough"'));
check('Study limitations and illustrative status are visible',html.includes('no control group')&&html.includes('not a patient case'));
check('Focused campaign preview shares the retained canonical',fs.readFileSync('dist/speech-campaign.html','utf8').includes('rel="canonical" href="'+canonical+'"'));
const og = html.match(/property="og:image" content="([^"]+)"/)[1];
check('Share image built under the owned asset namespace', new URL(og).pathname.startsWith('/pinnacle-pages-assets/') && fs.existsSync(path.join(root,'dist',new URL(og).pathname)));
check('Large social card with descriptive alt', html.includes('name="twitter:card" content="summary_large_image"') && html.includes('property="og:image:alt"'));
const imageTags = [...html.matchAll(/<img\b[^>]*>/g)].map(m=>m[0]);
check('Every image has alt text and fixed dimensions', imageTags.every(t=>/alt="[^"]+"/.test(t)&&/width="\d+"/.test(t)&&/height="\d+"/.test(t)));
check('Illustrative alt retained without intrusive AI captions', html.includes('Illustrative scene of a mother') && !html.includes('AI-generated') && !html.includes('not an actual patient'));
const assets = new Set([...html.matchAll(/(?:src|href)="(\/(?:pinnacle-pages-assets|pinnacle-pages-fonts|pinnacle-pages-scripts)\/[^"?#]+)"/g)].map(m=>m[1]));
const assetChecks=[];
for(const asset of assets){
 const response=await fetch('http://127.0.0.1:4326'+asset);
 check('Asset responds 200: '+path.basename(asset),response.status===200);
 assetChecks.push({asset,bytes:fs.statSync(path.join(root,'dist',asset)).size});
}
function luminance(hex){const rgb=hex.match(/[a-f\d]{2}/gi).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;}
const contrasts = Object.fromEntries(['e4115e','8f2879','665e69'].map(c=>[c,+(1.05/(luminance(c)+.05)).toFixed(2)]));
check('Primary palette has at least 4.5:1 contrast with white',Object.values(contrasts).every(r=>r>=4.5));
const report={checkedAt:new Date().toISOString(),build:'local sales preview',productionDeployed:false,checksPassed:checks.length,checks,htmlBytes:Buffer.byteLength(html),htmlGzipBytes:gzipSync(html).length,assets:assetChecks,contrastWithWhite:contrasts,notMeasured:['Field Core Web Vitals','Search rankings or AI citations','Connected calls','Accepted leads or enrolments']};
fs.writeFileSync(path.join(root,'SALES-VALIDATION-20260927.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
