'use strict';
module.exports=({e,icon})=>{
 const data=require('../content/assurance-map.json'),route='/evidence/assurance-map.html';
 const reportLink=(r)=>`<a href="/evidence/records/${r.id}.html">${e(r.id==='sae3000'?'SAE 3000 · limited assurance':'SRS 4400 · factual findings')}<br><strong>UDIN ${r.udin}</strong></a>`;
 const summary=`<div class="assurance-guide"><p class="eyebrow">INDEPENDENT CA REPORTS · SOURCE PAGES CONNECTED</p><h3>Documented scale. Traceable findings.</h3><p><strong>NPSY &amp; Co., Chartered Accountants</strong> examined specified institutional claims and issued two signed reports. The reports record 31,052,382 services, 792,614 beneficiary/family registrations and 2.7 billion+ structured records under their stated definitions.</p><p>Signed <strong>3 September 2026</strong> · records as at <strong>17 July 2026</strong> · N Prasada Rao, Partner (membership 200027; firm 013580S).</p><div class="citation-actions">${data.reports.map(reportLink).join('')}</div><p><a class="outline-link" href="${route}">${icon('file-search')}See what each report covers</a></p></div>`;
 const cards=group=>data.claims.filter(c=>c.group===group).map(c=>`<details class="claim-entry" id="claim-${c.id}"><summary><span>${e(c.title)}</span>${icon('plus')}</summary><div><p><strong>${e(c.summary)}</strong></p><p>${e(c.coverage)}</p><p>${e(c.definition)}</p><dl><div><dt>SAE 3000</dt><dd>${e(c.sourcePages.sae3000)}</dd></div><div><dt>SRS 4400</dt><dd>${e(c.sourcePages.srs4400)}</dd></div><div><dt>September handout</dt><dd>Physical PDF page${c.sourcePages.handout.length>1?'s':''} ${c.sourcePages.handout.join(', ')}</dd></div></dl><div class="citation-actions">${c.relatedRecords.map(id=>`<a href="/evidence/records/${id}.html">Read ${e(id.replaceAll('-',' '))} evidence</a>`).join('')}</div></div></details>`).join('');
 const content=`<p class="eyebrow">INDEPENDENT PRACTITIONER EVIDENCE</p><h1>Every claim connected<br>to the right evidence.</h1><p class="intro-copy">${e(data.summary)}</p>${summary}<section id="how-to-read"><h2>Two reports. Two kinds of evidence.</h2><p><strong>SAE 3000</strong> gives limited assurance over the enumerated assertions against the Board-adopted criteria. <strong>SRS 4400</strong> records the findings of agreed procedures; it does not express an audit opinion or an assurance conclusion.</p><p>ICAI provides the standards and UDIN verification mechanism. The independent report issuer is NPSY &amp; Co. The UDIN identifies its report; the report and annexures define what was examined.</p><p>Website source inspection: 19 September 2026. Both signed reports and their annexures were inspected. Both UDINs were matched in the live ICAI portal on 19 September 2026 and showed <strong>Active</strong>, with practitioner and signing particulars matching the supplied references. <a href="/evidence/issuer-checks.json">Read the dated verification record</a>. <a href="https://udin.icai.org/">Open ICAI’s UDIN portal</a>.</p></section><section id="report-coverage"><h2>Within the specified report scope</h2><p>Open a claim for its exact count or documentary finding, counting definition and source page.</p>${cards('Within the specified report scope')}</section><section id="separate-evidence"><h2>Evidence beyond these two reports</h2><p>Pinnacle’s wider evidence includes licences, facility records, publications and research. These use their own sources and dates. Outcome-study figures, ratings and financial statements are expressly outside the SAE assurance conclusion.</p>${cards('Separate source evidence')}</section><section id="reuse-map"><h2>Reference this map</h2><p>The signed reports carry use and circulation conditions. This page provides a scope summary and page references; enquiries about the complete reports can be sent to <a href="mailto:care@pinnacleblooms.org?subject=Independent%20CA%20report%20enquiry">care@pinnacleblooms.org</a>.</p><div class="citation-actions"><a href="/evidence/assurance-map.json">Download structured evidence map</a><a href="/evidence/assurance-map.txt">Read plain-text evidence map</a></div></section>`;
 const text='# '+data.title+'\n\n'+data.summary+'\nIssuer: '+data.issuer+'\nSignatory: '+data.signatory+'\nSigned: '+data.signedDate+'\nCutoff: '+data.subjectDate+'\n'+data.reviewMethod+'\n\n'+data.reports.map(r=>r.title+'\nUDIN: '+r.udin+'\n'+r.nature+'\n'+r.scope).join('\n\n')+'\n\n'+data.claims.map(c=>'## '+c.title+'\n'+c.group+'\n'+c.summary+'\n'+c.coverage+'\n'+c.definition+'\nSAE 3000: '+c.sourcePages.sae3000+'\nSRS 4400: '+c.sourcePages.srs4400+'\nHandout physical PDF pages: '+c.sourcePages.handout.join(', ')).join('\n\n');
 return {data,route,summary,content,text};
};
