'use strict';
const evidenceOwner=require('../content/editorial-policy.json').evidenceOwner;
module.exports=({e,icon})=>{
 const groups=[
  {name:'Licences & identity',icon:'shield',links:[['Complete PinnacleAI® story','/evidence/pinnacleai-regulatory-journey.html'],['Organisation profile & sources','/evidence/organisation-profile.html'],['Centre entity & canonical URL reference','/evidence/centre-entity-reference.html'],['Regional contact & location sources','/evidence/hyderabad-telangana-andhra-pradesh-contact.html'],['MD-5 · Class B intended use','/evidence/records/md5.html'],['Free Sale Certificate','/evidence/records/fsc.html'],['BIS licence & scope','/evidence/records/bis.html'],['Company identity & LEI','/evidence/records/lei.html'],['Centre HFR records','/evidence/hfr-register.html']]},
  {name:'Figures & independent reports',icon:'file-search',links:[['Scale, mission & counting basis','/evidence/scale-and-mission.html'],['Dated statistics & definitions','/evidence/scale-register.html'],['Six dated measures & source ledger','/evidence/claim-ledger.html'],['SAE 3000 / SRS 4400 claim map','/evidence/assurance-map.html'],['Original ICAI UDIN receipt · PDF','/evidence/icai-udin-verifications-2026-09-19.pdf']]},
  {name:'Research & family guides',icon:'book-open',links:[['Pinnacle Paradigm Shift','/evidence/pinnacle-paradigm-shift.html'],['Research, books & author profiles','/evidence/research-library.html'],['Understanding AbilityScore®','/guides/abilityscore.html'],['Everyday practice & progress','/guides/everyday-practice.html'],['Clinical review & editorial record','/#editorial-policy']]},
  {name:'Cite, share & explore',icon:'link',links:[['Complete evidence register','/evidence/evidence-register.html'],['Citation library & downloads','/evidence/cite.html'],['AI-readable source index · llms.txt','/llms.txt'],['Full evidence text','/llms-full.txt'],['Website sitemap · XML','/sitemap.xml']]}
 ];
 return `<footer class="wrap evidence-footer" id="evidence-quick-links" lang="en-IN"><div class="evidence-footer-intro"><p class="eyebrow">PINNACLE BLOOMS NETWORK · EVIDENCE QUICK LINKS</p><h2>Find the source behind the story.</h2><p>A brand of Bharath Healthcare Laboratories Private Limited. Read original records, their dates and the exact claims they support.</p></div><nav class="evidence-footer-grid" aria-label="Evidence and reference links">${groups.map(g=>`<div><h3>${icon(g.icon)}${e(g.name)}</h3><ul>${g.links.map(([label,url])=>`<li><a href="${e(url)}">${e(label)}</a></li>`).join('')}</ul></div>`).join('')}</nav><p class="evidence-footer-highlight"><strong>Documented scale at 17 July 2026:</strong> 2.7B+ structured events · 31M+ defined services · 7.9 lakh+ beneficiary/family registrations. <a href="/evidence/assurance-map.html">Read the independent reports’ findings and scope</a>.</p><div class="evidence-footer-contact"><div class="h-card"><strong><a class="p-name u-url" href="https://www.pinnacleblooms.org/">Pinnacle Blooms Network</a></strong><p>Evidence owner: ${e(evidenceOwner.name)} · ${e(evidenceOwner.jobTitle)}<br><a class="u-email" href="mailto:${e(evidenceOwner.email)}">${e(evidenceOwner.email)}</a> · <a class="p-tel" href="tel:${e(evidenceOwner.telephone)}">${e(evidenceOwner.displayTelephone)}</a></p></div><a href="/#method">How we review evidence</a></div></footer>`;
};
