'use strict';
const workflow=require('../content/how-pinnacleai-works.json');
module.exports=({e,icon})=>{
 const steps=[
  ['observe','Observe','Start with everyday life.','A family wants to help their child express a choice during a familiar routine. They describe what the child already does, what interests them and where support helps.','Family contribution','Everyday observations give the care team context.','md5','Parents and caregivers in the intended use'],
  ['review','Review','Bring the observations together.','The family and professionals review the starting point and agree a useful goal. Pinnacle describes the Personal Development Kernel as the child-specific record connecting measurements, context and responses.','People + a connected record','The care team checks the goal and the support appropriate to this child.','dossier','Personal Development Kernel and human oversight'],
  ['report','Report','Make the starting point understandable.','The overall AbilityScore® report and seven readiness views help organise the discussion. The important connection is from the report to an agreed everyday goal.','One profile. Seven readiness views.','Explore what each report is for below. No individual child’s results are displayed here.','methodology','Read the measurement methods'],
  ['practise','Practise','Turn the goal into guided practice.','The documented Everyday Therapy™ programme links selected techniques with goals. In this illustration, the care team explains a communication activity within a familiar routine and agrees how the family can take part.','Guidance for the people around the child','The activity, support and practice schedule are agreed with the care team.','september-handout','Everyday Therapy programme description'],
  ['feedback','Give feedback','What happened during practice?','Feedback connects the experience at home with the next review. Try either response to see how the discussion can change.','An illustrative feedback example','This demonstration does not assess a child, prescribe an activity or generate a treatment plan.','dossier','Tracking, correction and human oversight'],
  ['next','Review again','Use the experience to shape the next plan.','The care team reviews feedback, adjusts goals or support, and discusses the next assessment. Monthly reassessment is described in the reviewed methodology and walkthrough.','Keep the child’s everyday life in view','Look for meaningful changes in communication, routines, learning and participation, alongside the scores.','methodology','Reassessment and methodology']
 ];
 const example=`<div class="demo-feedback"><div class="feedback-actions" hidden><button type="button" aria-pressed="false" data-demo-response="support">The activity needed more support</button><button type="button" data-demo-response="challenge">The child was ready for a new challenge</button></div><p class="demo-response" aria-live="polite">The care team reviews what happened, discusses the activity and support with the family, and agrees what to try next.</p><p class="demo-defaults">For a difficult activity, discuss a smaller step or more support. For an activity the child can manage, discuss a suitable next challenge. These are examples of a review conversation.</p></div>`;
 const tour=`<section class="experience-section wrap" id="experience" aria-labelledby="experience-title"><div class="experience-heading"><p class="eyebrow">THE CONNECTED JOURNEY · A ONE-MINUTE GUIDE</p><h2 id="experience-title">See how one observation<br>can inform the next step.</h2><p>Explore the documented process through an illustrative family scenario. This guide uses no child data and does not perform an assessment.</p></div><div class="experience-tabs" role="tablist" aria-label="Developmental workflow steps" hidden>${steps.map((s,i)=>`<button type="button" role="tab" id="tab-${s[0]}" aria-controls="experience-${s[0]}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-experience-step="${s[0]}"><span>0${i+1}</span>${e(s[1])}</button>`).join('')}</div><div class="experience-panels">${steps.map((s,i)=>`<div class="experience-panel" id="experience-${s[0]}" data-experience-panel="${s[0]}"><div class="experience-scene"><span class="experience-number">0${i+1}</span><p class="eyebrow">${e(s[1])}</p><h3>${e(s[2])}</h3><p>${e(s[3])}</p>${s[0]==='feedback'?example:''}</div><div class="experience-meaning">${icon(['scan-eye','users','files','house','chart-no-axes-combined','rotate-ccw'][i])}<h4>${e(s[4])}</h4><p>${e(s[5])}</p><a href="/evidence/records/${s[6]}.html" class="source-link">${icon('file-search')}${e(s[7])}</a></div></div>`).join('')}</div><div class="experience-controls" hidden><button type="button" data-experience-back>Previous</button><span class="experience-progress" aria-live="polite">Step 1 of 6</span><button type="button" data-experience-next>Next step →</button></div><div class="experience-links"><a href="#report-explorer">Explore the eight reports ${icon('arrow-up-right')}</a><a href="#how-pinnacleai-works">Read the full workflow and sources ${icon('arrow-up-right')}</a></div></section>`;
 const questions=[
  'Which abilities should we prioritise, and why?',
  'How can we support communication in everyday routines?',
  'What helps my child feel comfortable and take part?',
  'Which movement skills matter for my child’s routines?',
  'What support could make learning more accessible?',
  'What would help my child participate at school?',
  'Which everyday task could my child do with less help?',
  'What support would help my child join in with others?'
 ];
 const reports=`<section class="report-explorer wrap" id="report-explorer" aria-labelledby="report-explorer-title"><p class="eyebrow">UNDERSTAND THE REPORTS</p><h2 id="report-explorer-title">One overall profile.<br>Seven focused readiness views.</h2><p>The supplied report examples use a 0–1000 display scale. Explore what each view brings to a conversation about your child’s next steps.</p><div class="report-picker" hidden><label for="report-choice">Choose a report</label><select id="report-choice">${workflow.reportPack.reports.map((r,i)=>`<option value="report-view-${i}">${e(r.name)}</option>`).join('')}</select></div><div class="report-panels">${workflow.reportPack.reports.map((r,i)=>`<article class="report-view" id="report-view-${i}" data-report-panel><div class="report-sheet"><span class="report-document-label">REPORT GUIDE · ${i===0?'OVERALL PROFILE':'READINESS VIEW'}</span>${icon('files')}<h3>${e(r.name)}</h3><p>${e(r.meaning)}</p><div class="report-range"><span>0</span><span>Display scale</span><span>1000</span></div><p class="report-no-data">Format explained · no child scores shown</p></div><div class="report-conversation"><p class="eyebrow">A USEFUL QUESTION FOR YOUR CARE TEAM</p><h4>“${e(questions[i])}”</h4><p>Connect the report with what you observe, the agreed goals and the support your child needs. Review change over time with the care team.</p><a class="source-link" href="#child-report-pack">Report-format review and context ${icon('arrow-up-right')}</a><a class="source-link" href="#monthly-readiness-review">How reassessment connects ${icon('arrow-up-right')}</a></div></article>`).join('')}</div><p class="report-footnote">${e(workflow.reportPack.interpretation)} Report presentation version V-1.6.9.9 is separate from the SaMD software version.</p></section>`;
 const proof=`<section class="proof-map wrap" id="proof-map"><p class="eyebrow">FOLLOW THE EVIDENCE</p><h2>A clear source for each kind of question.</h2><div class="proof-map-grid">${[
 ['file-cog','What is the licensed purpose?','MD-5 names the non-diagnostic Class B software’s intended use and users.','/evidence/records/md5.html','Read the intended use'],
 ['shield','How are the modules connected?','The BIS schedule names the quality-system scope and developmental modules.','/evidence/records/bis.html','Inspect the BIS schedule'],
 ['flask-conical','What has been studied?','Explore published methods, study summaries and protocols with their research status.','/evidence/research-library.html','Explore research and authors'],
 ['map-pin','What supports the scale and network?','Follow each metric to its reporting basis, and each centre to its supplied records.','/evidence/scale-register.html','See figures, definitions and sources']
 ].map(x=>`<article>${icon(x[0])}<h3>${e(x[1])}</h3><p>${e(x[2])}</p><a href="${x[3]}" class="source-link">${e(x[4])} ${icon('arrow-up-right')}</a></article>`).join('')}</div><a class="source-link" href="#records">Search all 34 evidence records ${icon('arrow-up-right')}</a></section>`;
 const audience=`<nav class="audience-paths wrap" id="start-here" aria-label="Choose your reading path"><a href="#experience"><span>FOR FAMILIES</span><strong>Understand the journey</strong><small>See the process and explore the reports ${icon('arrow-up-right')}</small></a><a href="/evidence/research-library.html"><span>FOR PROFESSIONALS</span><strong>Examine the research</strong><small>Methods, studies, authors and scope ${icon('arrow-up-right')}</small></a><a href="#proof-map"><span>FOR PARTNERS & EVALUATORS</span><strong>Inspect the evidence</strong><small>Licences, documented scale and centre records ${icon('arrow-up-right')}</small></a></nav>`;
 const data={kind:'Illustrative workflow and report guide',assessment:false,steps:steps.map(s=>({id:s[0],action:s[1],title:s[2],description:s[3],meaning:s[5],evidence:'/evidence/records/'+s[6]+'.html'})),reports:workflow.reportPack.reports.map((r,i)=>({...r,question:questions[i]}))};
 const text='# PinnacleAI® guided explanation\nAn illustrative guide to the documented workflow; no child data, assessment or product recording.\n'+data.steps.map(s=>s.title+'\n'+s.description+'\n'+s.meaning+'\nSource: https://www.pinnacleblooms.org/verify'+s.evidence).join('\n\n')+'\n\nReport explorer\n'+data.reports.map(r=>r.name+': '+r.meaning+'\nQuestion for the care team: '+r.question).join('\n\n');
 return {tour,reports,proof,audience,data,text};
};
