'use strict';
const data=require('../content/hfr-register.json');
module.exports=({e,icon})=>{
 const summary=`<div class="hfr-summary"><div><strong>${data.counts.workbookRows}</strong><span>centres in the supplied workbook</span></div><div><strong>${data.counts.combinedIds}</strong><span>distinct HFR IDs across both sources</span></div><div><strong>${data.counts.certificateIds}</strong><span>IDs with inspected certificate copies</span></div></div>`;
 const note='All 52 workbook rows are included. Twenty-seven IDs match the certificate collection; 25 are additional workbook entries. One further Tirupati certificate makes 53 distinct IDs across the two sources. These totals do not establish the number of currently operating centres.';
 const rows=data.rows.map(r=>`<tr id="hfr-${e(r.id)}" data-hfr-search="${e([r.name,r.id,r.address,r.postcode].join(' ').toLowerCase())}"><th scope="row" data-label="Centre">${e(r.name)}</th><td data-label="HFR identifier"><strong>${e(r.id)}</strong><span class="hfr-source-level">${e(r.sourceLevel)}</span></td><td data-label="Address supplied">${e(r.address)}${r.postcode?`<small>Postcode column: ${e(r.postcode)}</small>`:''}</td><td data-label="Source and printed date">${r.workbookRow?`Workbook row ${r.workbookRow}<small>RS flag as supplied: ${e(r.sourceFlag)}</small>`:'Additional certificate; absent from workbook'}${r.certificate?`<p>Certificate date: ${e(r.certificate.date)}<br>Recognitions bundle p${e(r.certificate.pages)}</p>`:'<p>Certificate copy not in the inspected collection.</p>'}</td></tr>`).join('');
 const content=`<p class="eyebrow">COMPLETE SUPPLIED CENTRE INVENTORY</p><h1>Every listed centre.<br>Its HFR identifier and source.</h1><p class="intro-copy">All 52 entries in the supplied workbook, reconciled with the original certificate collection. Reviewed 18 September 2026.</p>${summary}<p>${note}</p><div class="hfr-tools"><label for="hfr-search">Find a centre, address, postcode or HFR identifier<input id="hfr-search" type="search" placeholder="Suchitra, Bengaluru, IN3610023010…"></label><p id="hfr-result" role="status" aria-live="polite">53 HFR records</p><a class="outline-link" href="/evidence/hfr-register.csv">${icon('download')}Download all records · CSV</a></div><div class="hfr-table"><table><caption>Complete source inventory. Workbook flags do not indicate verified current registry status.</caption><thead><tr><th>Centre</th><th>HFR identifier & source level</th><th>Address supplied</th><th>Source and printed date</th></tr></thead><tbody>${rows}</tbody></table></div><p id="hfr-empty" hidden>No records match. Try a shorter centre name or the complete HFR identifier.</p><section class="hfr-notes"><h2>How to read this register</h2><p>${e(data.scope)}</p><p>The source workbook contains 37 ACTIVE and 15 INACTIVE values under an undefined RS column. They are preserved as source flags, with no assumption about registration validity or whether a centre is open. Addresses and postcode columns are reproduced separately where the workbook supplies both; confirm the current premises with Pinnacle.</p><p>Tirupati IN2810065148 appears in the workbook. The additional original certificate IN2810053847 is kept separately. The source material does not establish that either replaces or cancels the other.</p><p><strong>Sources:</strong> ${e(data.source.workbook)}, sheet ${e(data.source.sheet)}, rows 2–53. Recognitions bundle, physical pages 67–95. The workbook has no date column; 18 September is the inspection date.</p><div class="record-actions"><a href="https://hfr.abdm.gov.in/" target="_blank" rel="noopener noreferrer">${icon('external-link')}Official ABDM HFR portal</a><a href="/evidence/hfr-register.json">${icon('files')}Source inventory · JSON</a><a href="/evidence/records/hfr.html">${icon('file-search')}HFR evidence record</a></div></section>`;
 const centres=data.rows.map(r=>({kind:'hfr',name:r.name,identifier:r.id,date:r.certificate?r.certificate.date:'No certificate date in inspected sources',source:r.workbookRow?'All Centers With HFR.xlsx · row '+r.workbookRow:'Recognitions bundle · p'+r.certificate.pages,note:r.workbookRow?'Workbook RS: '+r.sourceFlag+' (meaning undefined; not current registry status). '+(r.certificate?'Certificate copy also inspected.':'Workbook-listed identifier; certificate not in the inspected collection.'):'Additional certificate record retained separately from workbook; current registry status not queried.',address:r.address,postcode:r.postcode,sourceLevel:r.sourceLevel,sourceUrl:'/evidence/hfr-register.html#hfr-'+r.id,search:[r.name,r.id,r.address,r.postcode].join(' ').toLowerCase()}));
 const csvCell=s=>'"'+String(s??'').replaceAll('"','""')+'"';
 const csv=[['Centre','HFR identifier','Address supplied','Postcode supplied','Workbook row','Workbook RS flag (undefined)','Certificate date','Certificate source pages','Source level'],...data.rows.map(r=>[r.name,r.id,r.address,r.postcode,r.workbookRow,r.sourceFlag,r.certificate?.date,r.certificate?.pages,r.sourceLevel])].map(r=>r.map(csvCell).join(',')).join('\n')+'\n';
 return {data,summary,note,content,centres,csv};
};
