'use strict';
const evidenceOwner=require('../content/editorial-policy.json').evidenceOwner;
const data=require('../content/impact.json');
module.exports=({e,icon})=>{
 const source=id=>data.sources.find(s=>s.id===id);
 const cite=id=>{const s=source(id);return `<a class="source-link" href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${icon('external-link')}${e(s.name)}</a>`;};
 const evidence=(id,label='Read Pinnacle’s source record')=>`<a class="source-link" href="/evidence/records/${id}.html">${icon('file-search')}${e(label)}</a>`;
 const pillars=[
 ['scan-eye','A starting point you can understand.','Ability measurement and defined developmental goals help families ask what to work on and why.','md5'],
 ['users','A plan people can work on together.','Pinnacle describes a connected pathway across practitioners, parent-guided practice and progress review.','dossier'],
 ['house','Practice that belongs in everyday life.','The BIS schedule names parent-facing developmental-support modules alongside tracking and correction.','bis'],
 ['chart-no-axes-combined','Progress you can discuss.','Ask how changing abilities will inform the next plan, the next reassessment and participation goals.','methodology']
 ];
 const impact=`<section class="impact-section wrap" id="impact" aria-labelledby="impact-title"><p class="eyebrow">FROM DOCUMENTS TO EVERYDAY MEANING</p><div class="section-heading"><h2 id="impact-title">A clearer starting point.<br>A connected way forward.</h2><p>For a family, evidence becomes useful when it helps answer three questions: What can my child do now? What will we work on together? How will we understand what changes?</p></div><div class="impact-grid">${pillars.map(([i,h,p,r])=>`<article><span class="section-icon">${icon(i)}</span><h3>${h}</h3><p>${p}</p>${evidence(r)}</article>`).join('')}</div><div class="everyday-goals"><strong>Make the goals personal.</strong><p>Communicating a need. Joining a family routine. Taking turns. Participating at school. These are examples of goals to discuss—not promised results. The plan should reflect your child’s abilities, preferences and support needs.</p></div></section>`;
 const scale=`<section class="scale-section" id="data-scale"><div class="wrap"><p class="eyebrow">THE MEANING BEHIND THE SCALE</p><div class="scale-layout"><div><span class="metric-number">2.7 billion+</span><h2>Structured developmental records.<br>One child’s journey at a time.</h2><p class="metric-caption">Company-reported in the 7 September 2026 handout.<br>Counting basis: database rows/events · cutoff 17 July 2026.</p>${evidence('operating-metrics','See the dated metric and counting basis')}</div><div><h3>A developmental journey you can follow.</h3><p>Session entries, assessment observations, technique ratings and other platform events can preserve a record over time. The practical question is how that history helps the care team review your child’s plan.</p><p>Volume describes the size of the record system. Useful decisions also depend on data quality, consistent measurement, appropriate use and professional judgement.</p><div class="scale-boundary">This is not a count of unique children, independent clinical-trial observations or verified AI-training examples. A large count alone does not prove clinical effectiveness.</div></div></div><details class="context-disclosure"><summary>Why do some Pinnacle sources say 2.5 billion+ and others 2.7 billion+? ${icon('plus')}</summary><p>The July dossier used a 2.5 billion+ floor and retired earlier 2.7 billion wording. The September handout subsequently reports 2.7 billion+ observed row counts. The source review distinguishes the 2.5 billion floor assertion in limited assurance from the 2.7 billion factual row-count finding under agreed procedures. Those procedures do not provide an assurance opinion.</p><p>These are dated measures with different reporting roles. Neither should be described as an audited count of AI-training examples. Restricted practitioner reports are not republished here.</p>${evidence('operating-metrics')}</details></div></section>`;
 const regulatory=`<section class="regulatory-section wrap" id="regulated-purpose"><p class="eyebrow">A DEFINED PURPOSE. TRACEABLE RESPONSIBILITIES.</p><div class="section-heading"><h2>Understand what each<br>credential adds.</h2><p>An issued licence defines the software’s intended use. Quality records describe how the system is managed. The BIS schedule connects those processes to a broader set of developmental-support modules.</p></div><div class="regulatory-grid"><article><span class="section-icon">${icon('file-text')}</span><span class="conclusion-label">APPLICATION HISTORY</span><h3>MD-3</h3><p>The application for a manufacturing licence. It is part of the regulatory record, rather than a second approval.</p>${evidence('md3')}</article><article><span class="section-icon">${icon('file-cog')}</span><span class="conclusion-label">ISSUED MANUFACTURING LICENCE</span><h3>MD-5 · Class B</h3><p>Telangana DCA licence MFG/MD/2026/000248 lists PinnacleAI® GPT-OS v1.0.0 for non-diagnostic developmental support, ages 0–12.</p>${evidence('md5')}</article><article><span class="section-icon">${icon('network')}</span><span class="conclusion-label">SYSTEMS & MODULES</span><h3>BIS scope schedule</h3><p>The schedule names software development, deployment and maintenance, plus ability mapping, parent-guided practice, progress correction and readiness modules.</p>${evidence('bis')}</article></div><div class="licensed-functions"><h3>Four functions named in the MD-5 intended use</h3><ul><li>${icon('scan-eye')}Developmental ability measurement</li><li>${icon('chart-no-axes-combined')}Readiness tracking</li><li>${icon('clipboard-list')}Progress forecasting</li><li>${icon('rotate-ccw')}Adaptive therapy-plan support</li></ul><p>Parents, therapists, educators and caregivers are the intended users. The licensed software supports developmental work; it does not diagnose, approve every therapy centre or guarantee a child’s outcome.</p></div><p class="context-note">Class B is a risk classification under India’s rules. US FDA Class II is a different jurisdiction’s classification; neither is a universal ranking of quality or clinical superiority. ${cite('cdsco')}</p></section>`;
 const principles=`<section class="principles-section" id="global-principles"><div class="wrap"><p class="eyebrow">GLOBAL PRINCIPLES. PINNACLE’S DOCUMENTED APPROACH.</p><div class="section-heading"><h2>Why these capabilities<br>matter to families.</h2><p>Independent guidance explains the importance of monitoring, caregiver participation, coordinated support and inclusion. These organisations do not endorse or evaluate Pinnacle through the references below.</p></div><div class="principles-grid">${data.principles.map(p=>`<article><span class="section-icon">${icon(p.icon)}</span><h3>${e(p.title)}</h3>${p.quote?`<blockquote>“${e(p.quote)}”</blockquote>`:''}<p>${e(p.principle)}</p>${cite(p.source)}<div class="principle-connection"><span>Pinnacle connection</span><p>${e(p.connection)}</p>${evidence(p.record)}</div><p class="family-question"><strong>Ask the care team:</strong> ${e(p.question)}</p></article>`).join('')}</div></div></section>`;
 const rows=()=>data.comparators.map(c=>`<tr><th scope="row">${e(c.name)}<span>${e(c.lane)}</span></th><td data-label="Documented purpose">${e(c.scope)}</td><td data-label="Source and status">${e(c.evidence)}${cite(c.source)}</td><td data-label="How to read the comparison">${e(c.meaning)}</td></tr>`).join('');
 const comparisons=`<section class="global-section wrap" id="global-context"><p class="eyebrow">AUTISM AI & GLOBAL DEVELOPMENTAL CARE</p><div class="section-heading"><h2>See where Pinnacle fits.<br>Compare what matters.</h2><p>Different organisations address diagnosis, assessment, digital treatment, integrated services or provider software. A useful comparison starts with the job each is designed to do.</p></div><div class="pinnacle-position"><span class="section-icon">${icon('network')}</span><div><h3>Pinnacle’s documented combination</h3><p>Non-diagnostic developmental-support software with an issued MD-5, a BIS schedule naming connected developmental modules, and a company-described seven-stage care pathway. For families, the important connection is between measurement, a plan, everyday practice and review.</p>${evidence('md5','MD-5 intended use')} ${evidence('bis','BIS scope schedule')}</div></div><div class="comparison-table"><table><caption>Selected global approaches · primary-source review, 18 September 2026</caption><thead><tr><th>Organisation / approach</th><th>Documented purpose</th><th>Source and status</th><th>How to read the comparison</th></tr></thead><tbody>${rows()}</tbody></table></div><p class="context-note">This is a targeted review of five examples, not an exhaustive worldwide census or a head-to-head effectiveness study. It establishes no overall winner, cross-country regulatory equivalence, largest-dataset ranking or global exclusivity.</p><div class="comparison-takeaway"><h3>The better comparison question</h3><p>“Which combination of measurement, professional support, home practice, progress review and participation goals is actually available for my child—and can I inspect the evidence?”</p><a class="outline-link" href="/evidence/global-context.html">${icon('book-open')}Read the full context and sources</a></div></section>`;
 const cta=`<section class="next-step-section wrap" id="next-step"><span class="section-icon">${icon('users')}</span><div><p class="eyebrow">BEGIN WITH CLARITY</p><h2>Your child’s next step<br>deserves a clear conversation.</h2><p>Ask the Pinnacle team about your child’s starting abilities, the proposed goals, who coordinates care and when progress will be reviewed. Bring the evidence questions that matter to your family.</p></div><div class="next-step-actions"><a class="primary-link" href="tel:+919100181181">${icon('phone')}Speak with Pinnacle · 9100 181 181</a><a href="mailto:care@pinnacleblooms.org?subject=Understanding%20my%20child%E2%80%99s%20developmental%20support%20plan">${icon('mail')}care@pinnacleblooms.org</a><span>Evidence owner: ${e(evidenceOwner.name)} · ${e(evidenceOwner.jobTitle)}</span></div></section>`;
 const sourceList=`<section class="context-sources" id="context-sources"><h2>Sources you can inspect</h2><p>Regulator documents establish product indications. Provider pages describe their own services or dataset counts. International guidance supplies context, not a Pinnacle endorsement.</p><ol>${data.sources.map(s=>`<li>${cite(s.id)}<p>${e(s.scope)} <span>${e(s.date)}</span></p></li>`).join('')}</ol></section>`;
 const contextText='# Pinnacle: family relevance and global context\n\nReviewed: '+data.reviewed+'\n\n'+data.positioning+'\n\n'+data.principles.map(p=>`## ${p.title}\n${p.principle}\nPinnacle connection: ${p.connection}\nFamily question: ${p.question}\nSource: ${source(p.source).url}\n`).join('\n')+'\n## Selected global approaches\n'+data.comparators.map(c=>`${c.name}: ${c.scope}\nEvidence: ${c.evidence}\nComparison boundary: ${c.meaning}\nSource: ${source(c.source).url}\n`).join('\n')+'\nThis is a targeted comparison, not proof of global exclusivity or superiority.\n';
 return {data,impact,scale,regulatory,principles,comparisons,cta,sourceList,contextText};
};
