'use strict';
const languages=[['en','English'],['te','Telugu · తెలుగు'],['hi','Hindi · हिन्दी'],['kn','Kannada · ಕನ್ನಡ'],['ta','Tamil · தமிழ்'],['ml','Malayalam · മലയാളം'],['mr','Marathi · मराठी'],['bn','Bangla · বাংলা'],['gu','Gujarati · ગુજરાતી'],['pa','Punjabi · ਪੰਜਾਬੀ'],['or','Odia · ଓଡ଼ିଆ'],['ne','Nepali · नेपाली'],['ur','Urdu · اردو'],['ar','Arabic · العربية'],['es','Spanish · Español'],['fr','French · Français'],['de','German · Deutsch'],['pt','Portuguese · Português'],['zh-CN','Chinese · 中文'],['ja','Japanese · 日本語'],['ko','Korean · 한국어'],['id','Bahasa Indonesia'],['ru','Russian · Русский']];
module.exports=({e,icon,origin})=>{
 const utility=input=>{
  const url=new URL(input.replace(origin,'https://www.pinnacleblooms.org/verify'));
  url.search='';url.hash='';
  const guide=url.pathname.match(/^\/verify\/guides\/(?:(te|hi)\/)?(abilityscore|everyday-practice|licences-and-scope)\.html$/);
  const original=new URL(url.href);if(guide)original.pathname='/verify/guides/'+guide[2]+'.html';
  const current=guide?.[1]||'en';
  const native=guide?['en','te','hi'].map(code=>({code,url:'https://www.pinnacleblooms.org/verify/guides/'+(code==='en'?'':code+'/')+guide[2]+'.html',name:code==='en'?'English':code==='te'?'తెలుగు':'हिन्दी'})):[];
  return `<div class="reader-utility wrap notranslate reader-language-bar" translate="no"><a href="/evidence/cite.html">${icon('book-open')}Citations &amp; downloads</a><details class="language-menu"><summary>${icon('network')}Language &amp; reading</summary><div class="language-panel"><div role="group" aria-label="Choose a reading language" data-translate-form data-original-url="${encodeURIComponent(original.href)}" data-native-language="${current}"><label for="translation-language">Read in</label><select id="translation-language" name="tl">${languages.map(([code,name])=>`<option value="${code}"${current===code?' selected':''}>${e(name)}</option>`).join('')}</select><button type="button" data-read-language>Read ${icon('arrow-up-right')}</button></div><div class="reading-size" role="group" aria-label="Reading size"><span>Text</span><button type="button" data-reader-size="1" aria-pressed="true" aria-label="Standard text size">A</button><button type="button" data-reader-size="1.12" aria-pressed="false" aria-label="Larger text size">A+</button><button type="button" data-reader-size="1.25" aria-pressed="false" aria-label="Largest text size">A++</button></div><div class="language-originals"><a href="${e(original.href)}" target="_top" data-read-original>English original</a>${native.filter(n=>n.code!=='en').map(n=>`<a href="${n.url}" lang="${n.code}" hreflang="${n.code}-IN" target="_top" data-native-language-link="${n.code}">${n.name} guide</a>`).join('')}<a href="https://translate.google.com/translate?sl=auto&amp;tl=te&amp;u=${encodeURIComponent(original.href)}" target="_top" data-more-languages>More languages</a></div><p class="language-note">${guide?'English, Telugu and Hindi have dedicated guide editions. Other languages use Google Translate.':'Choose English to return to the original. Other languages use Google Translate.'} Original documents remain the reference.</p><p class="visually-hidden" role="status" data-reader-status></p></div></details></div>`;
 };
 return {languages,utility};
};
module.exports.languages=languages;
