'use strict';
const data=require('../content/metrics.json');
module.exports=({e,icon})=>{
 const link=(x)=>`<a class="source-link" href="/evidence/records/${e(x.id)}.html">${icon('file-search')}${e(x.label)}</a>`;
 const cards=data.metrics.map(m=>`<article class="metric-card" id="${e(m.id)}"><div class="metric-heading"><span class="section-icon">${icon(m.icon)}</span><span class="metric-status">${e(m.status)}</span></div><strong class="metric-value">${e(m.value)}</strong><h3>${e(m.label)}</h3><p class="metric-meaning">${e(m.meaning)}</p><p class="metric-basis">${e(m.basis)}</p><details class="metric-detail"><summary>What this figure counts ${icon('plus')}</summary><p>${e(m.boundary)}</p></details><div class="metric-evidence">${m.evidence.map(link).join('')}</div></article>`).join('');
 const section=`<section class="metrics-section wrap" id="scale" aria-labelledby="scale-title"><p class="eyebrow">THE SCALE. THE MEANING. THE EVIDENCE.</p><div class="section-heading"><h2 id="scale-title">Every number should<br>lead to its source.</h2><p>Explore six measures of Pinnacle’s reported reach, activity and resources. Each keeps its counting unit, date and evidence type visible, so scale can be understood in the context of one child’s care.</p></div><div class="metrics-grid">${cards}</div><div class="metric-proof"><div><h3>${icon('file-search')}How the evidence connects</h3><p><strong>UDIN</strong> identifies a practitioner’s report. <strong>HFR</strong> identifies a health facility. A company publication or management update supplies a stated figure. Each answers a different verification question.</p></div><dl><div><dt>SAE 3000 · limited assurance</dt><dd><a href="/evidence/records/sae3000.html">26200027GMBLXU4868</a></dd></div><div><dt>SRS 4400 · factual findings</dt><dd><a href="/evidence/records/srs4400.html">26200027HCNFEI9138</a></dd></div></dl><p class="metric-proof-note">Reports inspected; UDIN particulars have not been independently matched in this review. A UDIN does not expand a report’s scope or validate a clinical outcome. <a href="https://udin.icai.org/" target="_blank" rel="noopener noreferrer">ICAI UDIN portal ${icon('external-link')}</a></p></div><div class="metric-footer"><a class="outline-link" href="/evidence/scale-register.html">${icon('book-open')}Full statistics & evidence register</a><a href="#centres">${icon('map-pin')}Explore the complete supplied centre list</a></div></section>`;
 const text='# Pinnacle scale: figures, definitions and evidence\n\nReviewed: '+data.reviewed+'\n\n'+data.metrics.map(m=>`## ${m.value} — ${m.label}\n${m.status}\n${m.meaning}\nCounting basis: ${m.basis}\nEvidence boundary: ${m.boundary}\nSources: ${m.evidence.map(x=>x.id).join(', ')}\n`).join('\n');
 return {data,section,text};
};
