'use strict';
const {whatsapp}=require('./contact-content.cjs');
const route='/evidence/pinnacle-paradigm-shift.html';
const title='Pinnacle Paradigm Shift | One Child, One Connected Plan';
const description='How PinnacleAI® connects ability measurement, a personal plan, everyday practice and progress review toward self-sufficiency and mainstream participation.';
const stages=[
 ['scan-eye','Understand abilities','Start with what your child can do today.','AbilityScore® brings observations into a structured starting point for discussion with the care team.','sovereign-walkthrough','Measurement framework'],
 ['clipboard-list','Agree a personal plan','Choose the abilities that matter in everyday life.','The Personal Development Kernel connects the child’s history, goals and responses; Prognose® supports readiness planning.','dossier','Planning and child-specific record'],
 ['users','Connect the care team','Give professional support a shared direction.','Therapists, educators, parents and caregivers contribute different perspectives around the child’s agreed goals.','md5','Named users and intended use'],
 ['house','Practise in daily life','Carry the plan into familiar routines.','The documented Everyday Therapy™ programme describes 7–9 selected techniques a day, with guidance appropriate to the child.','september-handout','Everyday programme · pages 5–7'],
 ['chart-no-axes-combined','Track and correct','Let what happens at home inform the next step.','The Fusion Module brings family and professional feedback into review of the activities, support and plan.','bis','Tracking and correction in scope'],
 ['rotate-ccw','Reassess and repeat','See what changed. Decide what comes next.','The published methodology describes monthly reassessment. Review the child’s progress and adapt priorities with the care team.','methodology','Published review methodology'],
 ['network','Grow toward participation','Keep the purpose in view: a wonderful life.','Work toward communication, daily-living abilities, school readiness and participation, with the support and accommodations each child needs.','bis','Self Sufficiency and Mainstream Inclusion']
];
const questions=[
 {question:'What does Pinnacle mean by a paradigm shift?',answer:'Pinnacle uses the term for a connected approach to child development: begin with everyday-life goals, measure abilities, agree a personal plan, connect professional support and home practice, then track, correct and reassess. The phrase describes its approach; it is not a claim of worldwide exclusivity.',sourceHref:'/evidence/records/dossier.html'},
 {question:'How are parents included in the licensed intended use?',answer:'The MD-5 annexure names parents, therapists, educators and caregivers as intended users of non-diagnostic developmental-support software for children aged 0–12. It describes ability measurement, readiness tracking, progress forecasting and adaptive therapy-plan support. Family participation works alongside appropriate professional guidance.',sourceHref:'/evidence/records/md5.html'},
 {question:'What connects the approach to self-sufficiency and mainstream life?',answer:'The BIS scope names developmental mapping, planning, everyday therapy, tracking and correction, seven readiness indexes, Self Sufficiency and Mainstream Inclusion across the full developmental lifecycle. These named functions describe the direction and scope of the system; individual outcomes depend on the child and their care context.',sourceHref:'/evidence/records/bis.html'},
 {question:'What evidence supports the scale behind Pinnacle?',answer:'At 17 July 2026, the SRS 4400 report records 2.7 billion+ structured developmental events, 31,052,382 defined cumulative services and 792,614 beneficiary/family registrations. A separate SAE 3000 report provides limited assurance over specified institutional assertions. The claim map links each figure to its source page; these volume measures are distinct from child outcomes.',sourceHref:'/evidence/assurance-map.html'}
];
module.exports=({e,icon,origin})=>{
 const href=id=>'/evidence/records/'+id+'.html';
 const html=`<section class="paradigm-story" id="pinnacle-paradigm-shift" aria-labelledby="paradigm-title">
 <header class="paradigm-opening"><p class="eyebrow">PINNACLE PARADIGM SHIFT</p><h2 id="paradigm-title">You picture a life.<br><em>We build the plan around it.</em></h2><p class="paradigm-lead">Your child asking for what they need. Joining a classroom. Taking part in family life. Growing toward self-sufficiency, with the support they need.</p><p>That picture gives the plan its direction. PinnacleAI® connects measurement, people, daily practice and review around the abilities that matter to <strong>your child’s everyday life.</strong></p></header>
 <div class="paradigm-destination"><span>${icon('network')}</span><div><strong>One child. One connected plan.</strong><p>A shared direction toward self-sufficiency, mainstream participation and a wonderful life.</p></div></div>
 <div class="paradigm-metaphor"><h3>The parts matter. So does how they work together.</h3><p>When you picture a car, you picture where it can take you. The engine, steering and wheels each have a job—and need to work together. A child’s support plan needs that connection too: clear goals, coordinated care, practice beyond the session and a way to check what changes.</p></div>
 <div class="paradigm-path-heading"><p class="eyebrow">FROM A STARTING POINT TO EVERYDAY PARTICIPATION</p><h3>Seven stages. A plan that keeps learning.</h3></div>
 <ol class="paradigm-path">${stages.map(([i,n,meaning,detail,id,label],k)=>`<li><span class="paradigm-stage-icon" aria-hidden="true">${icon(i)}</span><div><span class="paradigm-stage-number">0${k+1}</span><h4>${e(n)}</h4><p>${e(meaning)}</p><details><summary>How it connects ${icon('plus')}</summary><p>${e(detail)}</p><a href="${href(id)}">${e(label)} ${icon('arrow-up-right')}</a></details></div></li>`).join('')}</ol>
 <div class="paradigm-return">${icon('rotate-ccw')}Practise → observe → review → adapt. Revisit the plan as your child grows.</div>
 <div class="paradigm-proof" aria-label="Three ways to examine the connected approach"><a href="${href('sovereign-walkthrough')}">${icon('network')}<strong>17 domains · 79 abilities · 349 skills</strong><span>A structured view of abilities and individual priorities.</span></a><a href="/#report-explorer">${icon('files')}<strong>One overall profile. Seven readiness views.</strong><span>Understand the reports and the questions to discuss.</span></a><a href="${href('bis')}">${icon('shield')}<strong>The lifecycle is named in the BIS scope.</strong><span>Read the modules, activities and exact licence scope.</span></a></div>
 <details class="paradigm-evidence"><summary>${icon('file-search')}The evidence behind this approach ${icon('plus')}</summary><div>${questions.map(q=>`<article><h3>${e(q.question)}</h3><p>${e(q.answer)}</p><a href="${q.sourceHref}">Read the original record and context ${icon('arrow-up-right')}</a></article>`).join('')}<p><a href="/evidence/research-library.html">Explore the research, its publication stages and original books</a></p></div></details>
 <div class="paradigm-next"><div><h3>Start with one everyday hope for your child.</h3><p>Ask how the assessment, home practice and next review will work toward it.</p></div><a class="primary-link contact-whatsapp" href="${e(whatsapp)}" data-contact-location="paradigm">${icon('phone')}Discuss my child’s next step</a></div>
 <p class="paradigm-scope">PinnacleAI® GPT-OS: non-diagnostic Class B developmental-support software, ages 0–12. The approach works toward individual goals; outcomes vary.</p>
 </section>`;
 const text=['# Pinnacle Paradigm Shift',description,'You picture a life. We build the plan around it.','One child. One connected plan. A shared direction toward self-sufficiency, mainstream participation and a wonderful life.',...stages.map(([,name,meaning,detail,id,label],i)=>`${i+1}. ${name}\n${meaning} ${detail}\n${label}: ${origin+href(id)}`),...questions.map(q=>`${q.question}\n${q.answer}\nSource: ${origin+q.sourceHref}`)].join('\n\n');
 const homeHtml=html.replace(/<header class="paradigm-opening">[\s\S]*?<\/header>/,'<span id="paradigm-title" class="sr-only">Pinnacle Paradigm Shift: one connected plan.</span>');
 return {route,title,description,html,homeHtml,text,questions,stages:stages.map(([,name,meaning,detail,id],i)=>({position:i+1,name,meaning,description:detail,source:origin+href(id)}))};
};
