'use strict';
module.exports=({e,origin,date,data,abstracts,citations,head,pageHeader,footer,breadcrumb,crumbsHTML,write})=>{
 const selected=data.records.filter(r=>r.id.startsWith('zenodo-')||r.type==='book');
 const pages=[];
 for(const r of selected){
  const detail=abstracts.records.find(x=>x.id===r.id),route='/evidence/publications/'+r.id+'.html',url=origin+route;
  const authors=r.authors.map(a=>typeof a==='string'?a:a.name),cover=data.covers.find(x=>x.id===r.id)?.variants?.at(-1);
  const primary=r.doiUrl||r.url,files=(r.files||[]).filter(f=>/\.pdf$/.test(f.name)||f.name==='Original book PDF');
  if(detail?.localPdf)files.unshift({name:'Read original PDF',url:detail.localPdf});
  const abstractText=detail?.abstractText||'',abstractLabel=detail?.abstractLabel||'Author-written abstract';
  const desc=`${r.title}. ${r.publicationStatus}. Authors, original source${r.doi?', DOI':''} and citation downloads.`;
  const article={'@type':r.type==='book'?'Book':r.type==='report'?'Report':'ScholarlyArticle','@id':url+'#publication',name:r.title,headline:r.title,url,description:r.scopeNote,creativeWorkStatus:r.publicationStatus,author:r.authors.map(a=>({'@type':'Person',name:typeof a==='string'?a:a.name,...(a.orcid?{sameAs:'https://orcid.org/'+a.orcid}:{})})),...(r.publicationDate?{datePublished:r.publicationDate}:{}),...(r.version?{version:r.version}:{}),...(r.doi?{identifier:{'@type':'PropertyValue',propertyID:'DOI',value:r.doi},sameAs:r.doiUrl}:{}),...(r.bookISBN?{isbn:r.bookISBN}:{}),...(abstractText&&abstractLabel==='Author-written abstract'?{abstract:abstractText}:{}),...(cover?{image:origin+cover.url}:{}),...(detail?.licenseUrl?{license:detail.licenseUrl}:{}),encoding:files.map(f=>({'@type':'MediaObject',encodingFormat:'application/pdf',contentUrl:new URL(f.url,origin).href})),isPartOf:{'@id':origin+'/evidence/research-library.html#page'}};
  const crumbs=[['Verify Pinnacle','/'],['Research library','/evidence/research-library.html'],[r.title,route]];
  const meta=r.type!=='book'&&abstractText&&abstractLabel==='Author-written abstract'?`<meta name="citation_title" content="${e(r.title)}">${authors.map(a=>`<meta name="citation_author" content="${e(a)}">`).join('')}${r.publicationDate?`<meta name="citation_publication_date" content="${r.publicationDate.replaceAll('-','/')}">`:''}${r.doi?`<meta name="citation_doi" content="${e(r.doi)}">`:''}${detail?.localPdf?`<meta name="citation_pdf_url" content="${origin+detail.localPdf}">`:''}`:'';
  const pageHead=head(r.title+' | Pinnacle Research',desc,url,[{'@type':'WebPage','@id':url+'#page',url,name:r.title,dateModified:date,mainEntity:{'@id':article['@id']}},article,breadcrumb(crumbs,url)]).replace('</head>',meta+'</head>');
  const fullAbstract=abstractText?`<section id="abstract"><h2>${e(abstractLabel)}</h2><div class="publication-abstract">${abstractText.split(/\n\s*\n/).filter(Boolean).map(p=>'<p>'+e(p.replace(/\n/g,' '))+'</p>').join('')}</div><p class="provenance-note">Text reproduced from the ${e(detail.abstractSourceLabel||'original publication')}. <a href="${e(detail.sourceUrl||primary)}">Read the source</a>. ${detail.licenseUrl?`Reproduced under <a href="${detail.licenseUrl}">CC BY 4.0</a>; original authors credited above. Paragraph formatting only; wording retained.`:''}</p></section>`:`<section id="about-publication"><h2>About this ${r.type==='book'?'book':'publication'}</h2><p>${e(r.scopeNote)}</p></section>`;
  const content=`<main class="wrap publication-page">${crumbsHTML(crumbs)}<p class="eyebrow">${e(r.publicationStatus)}</p><h1>${e(r.title)}</h1><p class="intro-copy">${e(authors.join(' · '))}</p><div class="publication-meta">${r.publicationDate?`<time datetime="${r.publicationDate}">${e(r.publicationDate)}</time>`:'<span>Publication date not established from the reviewed source</span>'}${r.version?`<span>Version ${e(r.version)}</span>`:''}${r.doi?`<a href="${e(r.doiUrl)}">DOI ${e(r.doi)}</a>`:''}${r.bookISBN?`<span>ISBN ${e(r.bookISBN)}</span>`:''}</div><p>${e(r.scopeNote)}</p>${detail?.versionNote?`<p class="evidence-note">${e(detail.versionNote)}</p>`:''}<div class="publication-layout"><div>${fullAbstract}<section id="original-sources"><h2>Read the original</h2><div class="citation-actions">${primary?`<a href="${e(primary)}">${r.doi?'DOI record':'Publisher listing'}</a>`:''}${files.map(f=>`<a href="${e(f.url)}">${e(f.name==='Original book PDF'?'Original book PDF':f.name)}</a>`).join('')}</div><p>Bibliographic source checked ${e(detail?.reviewedOn||data.asOf)}. Publication status and author statements are retained as attributed source content.</p></section>${citations.controls(r.id)}</div>${cover?`<aside><img class="publication-cover" src="${cover.url}" width="${cover.width}" height="${cover.height}" alt="Original publication cover: ${e(r.title)}" loading="lazy" decoding="async"></aside>`:''}</div><p><a href="/evidence/research-library.html#authors">Author profiles and related publications</a></p></main>`;
  write(route.slice(1),'<!doctype html><html lang="en-IN">'+pageHead+'<body>'+pageHeader+content+footer+'</body></html>');
  pages.push({id:r.id,route,url,title:r.title,abstractText,abstractLabel,status:r.publicationStatus});
 }
 return pages;
};
