'use strict';
module.exports=({e,icon,origin,date,organization,website,brand,head,pageHeader,footer,breadcrumb,crumbsHTML,write,paradigm})=>{
 const profile=require('./organisation-profile-content.cjs');
 const referenceRoute='/evidence/organisation-profile.html';
 const renderPage=(route,title,description,content,questions,type='WebPage',citations=[])=>{
  const url=origin+route,crumbs=[['Verify Pinnacle','/'],[title.split(' | ')[0],route]];
  const graph=[organization,website,brand,{'@type':type,'@id':url+'#page',name:title,url,description,dateModified:date,inLanguage:'en-IN',publisher:{'@id':organization['@id']},mainEntity:{'@id':organization['@id']},citation:citations.map(x=>new URL(x,origin).href)},breadcrumb(crumbs,url)];
  if(questions.length)graph.push({'@type':'FAQPage','@id':url+'#quick-answers',mainEntity:questions.map((q,i)=>({'@type':'Question',name:q.question,'@id':url+'#answer-'+(i+1),acceptedAnswer:{'@type':'Answer',text:q.answer}}))});
  write(route.slice(1),'<!doctype html><html lang="en-IN">'+head(title,description,url,graph)+'<body>'+pageHeader+'<main class="wrap record-page '+(route===referenceRoute?'organisation-profile':'paradigm-page')+'">'+crumbsHTML(crumbs)+content+'</main>'+footer+'</body></html>');
 };
 const faq=(questions)=>`<section class="faq-section" id="quick-answers"><h2>Questions, answered with context.</h2>${questions.map((q,i)=>`<details class="faq-item" id="answer-${i+1}"><summary>${e(q.question)}${icon('plus')}</summary><div><p>${e(q.answer)}</p>${q.sourceHref?`<a href="${q.sourceHref}">Read the source</a>`:''}</div></details>`).join('')}</section>`;
 const paradigmHTML=paradigm.html.replace('<h2 id="paradigm-title">','<h1 id="paradigm-title" class="paradigm-page-title">').replace('We build the plan around it.</em></h2>','We build the plan around it.</em></h1>');
 const citation=`Bharath Healthcare Laboratories Private Limited. (2026, September 21). Pinnacle Paradigm Shift: one child, one connected plan. Pinnacle Verify. ${origin+paradigm.route}`;
 const citeBlock=`<section class="reference-citation" id="cite-this-approach"><h2>Cite this explanation</h2><p>${e(citation)}</p><p><a href="/evidence/pinnacle-paradigm-shift.txt">Readable explanation and sources</a> · <a href="/evidence/pinnacle-paradigm-shift.json">Structured reference</a></p></section>`;
 renderPage(paradigm.route,paradigm.title,paradigm.description,paradigmHTML+faq(paradigm.questions)+citeBlock,paradigm.questions,'WebPage',paradigm.stages.map(s=>s.source));
 const links=sources=>`<p class="profile-source-links">${sources.map((url,i)=>`<a href="${e(url)}">Source ${i+1} ${icon('arrow-up-right')}</a>`).join(' · ')}</p>`;
 const profileCitation=`Bharath Healthcare Laboratories Private Limited. (2026, September 21). Pinnacle Blooms Network: organisation profile. Pinnacle Verify. ${origin+referenceRoute}`;
 const profileHTML=`<header><p class="eyebrow">ORGANISATION PROFILE · FACTS & SOURCES</p><h1>Pinnacle Blooms Network</h1><p class="intro-copy">Identity. Purpose. Documented work.</p><p class="profile-intro">${e(profile.summary)}</p><div class="profile-downloads"><a href="/evidence/organisation-profile.txt">${icon('file-text')}Download the reference brief</a><a href="/evidence/organisation-profile.json">${icon('files')}Structured facts & sources</a><a href="/evidence/pinnacle-paradigm-shift.html">${icon('network')}Understand the approach</a></div></header><dl class="profile-facts">${profile.facts.map(f=>`<div><dt>${e(f.label)}</dt><dd>${e(f.value)}<br><a href="${f.sourceHref}">Read the source ${icon('arrow-up-right')}</a></dd></div>`).join('')}</dl>${profile.sections.map((s,i)=>`<section class="profile-section" id="profile-section-${i+1}"><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${links(s.sourceHrefs)}</section>`).join('')}${faq(profile.questions)}<section class="reference-citation" id="cite-organisation"><h2>Cite this profile</h2><p>${e(profileCitation)}</p><p>This is Pinnacle’s own reference publication. For a specific finding, cite the original source linked alongside that fact.</p></section>`;
 renderPage(referenceRoute,profile.title,profile.description,profileHTML,profile.questions,'AboutPage',profile.facts.map(f=>f.sourceHref));
 const profileText=['# '+profile.title,profile.summary,...profile.facts.map(f=>`${f.label}: ${f.value}\nSource: ${origin+f.sourceHref}`),...profile.sections.map(s=>`## ${s.title}\n${s.body}\n${s.sourceHrefs.map(h=>origin+h).join('\n')}`),...profile.questions.map(q=>q.question+'\n'+q.answer),profileCitation].join('\n\n');
 write('evidence/organisation-profile.txt',profileText+'\n');
 write('evidence/organisation-profile.json',JSON.stringify({...profile,canonical:origin+referenceRoute,updated:date,publisher:organization.name,sourceType:'First-party reference profile',citation:profileCitation},null,2));
 write('evidence/pinnacle-paradigm-shift.txt',paradigm.text+'\n\n'+citation+'\n');
 write('evidence/pinnacle-paradigm-shift.json',JSON.stringify({title:paradigm.title,description:paradigm.description,canonical:origin+paradigm.route,updated:date,publisher:organization.name,sourceType:'Source-linked company explanation',stages:paradigm.stages,questions:paradigm.questions,citation},null,2));
 return {routes:[paradigm.route,referenceRoute],text:paradigm.text+'\n\n'+profileText,index:`\n## Pinnacle approach and organisation reference\n- [Pinnacle Paradigm Shift](${origin+paradigm.route}): one child, one connected plan; seven stages, named software functions and source-linked answers.\n- [Organisation profile](${origin+referenceRoute}): brand, legal entity, corporate history, software scope, dated figures, publications and editorial responsibility.\n- [Organisation profile JSON](${origin}/evidence/organisation-profile.json): the same facts and source references.\n- [Connected approach JSON](${origin}/evidence/pinnacle-paradigm-shift.json): the same seven stages and evidence-linked answers.\n`};
};
