'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
module.exports=({e,icon,origin,date,organization,website,brand,head,pageHeader,footer,breadcrumb,crumbsHTML,write,paradigm,storyDeck})=>{
 const profile=require('./organisation-profile-content.cjs');
 const pack=require('../content/public-evidence-pack.json');
 const packFile=path.join(__dirname,'..','dist',pack.path.slice(1));
 const packHash=crypto.createHash('sha256').update(fs.readFileSync(packFile)).digest('hex');
 if(packHash!==pack.sha256)throw Error('Public evidence pack does not match its reviewed safe hash.');
 const story=require('../content/paradigm-story.json');
 const referenceRoute='/evidence/organisation-profile.html';
 const regionalRoute='/evidence/hyderabad-telangana-andhra-pradesh-contact.html';
 const centreEntityRoute='/evidence/centre-entity-reference.html';
 const regionalUpdated='2026-09-23';
 const renderPage=(route,title,description,content,questions,type='WebPage',citations=[],extraGraph=[],mainEntityId=organization['@id'])=>{
  const url=origin+route,crumbs=[['Verify Pinnacle','/'],[title.split(' | ')[0],route]];
  const currentReference=[referenceRoute,regionalRoute,centreEntityRoute].includes(route);
  const datedHeader=currentReference?pageHeader.replace(/Updated: \d{1,2} [A-Za-z]+ \d{4}/,'Updated: 23 September 2026'):pageHeader;
  const graph=[organization,website,brand,{'@type':type,'@id':url+'#page',name:title,url,description,dateModified:currentReference?regionalUpdated:date,inLanguage:'en-IN',publisher:{'@id':organization['@id']},mainEntity:{'@id':mainEntityId},citation:citations.map(x=>new URL(x,origin).href)},breadcrumb(crumbs,url),...extraGraph];
  if(questions.length)graph.push({'@type':'FAQPage','@id':url+'#quick-answers',mainEntity:questions.map((q,i)=>({'@type':'Question',name:q.question,'@id':url+'#answer-'+(i+1),acceptedAnswer:{'@type':'Answer',text:q.answer}}))});
  write(route.slice(1),'<!doctype html><html lang="en-IN">'+head(title,description,url,graph)+'<body>'+datedHeader+'<main class="wrap record-page '+(currentReference?'organisation-profile':'paradigm-page')+'">'+crumbsHTML(crumbs)+content+'</main>'+footer+'</body></html>');
 };
 const faq=(questions)=>`<section class="faq-section" id="quick-answers"><h2>Questions, answered with context.</h2>${questions.map((q,i)=>`<details class="faq-item" id="answer-${i+1}"><summary>${e(q.question)}${icon('plus')}</summary><div><p>${e(q.answer)}</p>${q.sourceHref?`<a href="${q.sourceHref}">Read the source</a>`:''}</div></details>`).join('')}</section>`;
 if(!storyDeck?.html||!Array.isArray(storyDeck.cardRoutes)||storyDeck.cardRoutes.length!==9||story.cards.length!==9)throw Error('The paradigm overview requires the complete nine-card system story.');
 const overviewTitle='Pinnacle Paradigm Shift | One Connected Care System';
 const overviewDescription='Nine perspectives on how PinnacleAI® connects measurement, plans, professional care, home practice and review, with original sources and a seven-stage pathway.';
 const overviewURL=origin+paradigm.route,approachId=overviewURL+'#approach';
 const storyHeading=/<h2 id="paradigm-story-heading">([\s\S]*?)<\/h2>/;
 if(!storyHeading.test(storyDeck.html))throw Error('The paradigm story overview needs its named heading.');
 const storyHTML=storyDeck.html.replace(storyHeading,'<h1 id="paradigm-story-heading" class="paradigm-page-title">$1</h1>');
 const paradigmHTML=`<div id="approach">${storyHTML}</div><div class="hero-share-slot paradigm-overview-share"></div><details class="context-disclosure paradigm-legacy" id="seven-stage-developmental-approach"><summary>See the seven-stage developmental pathway ${icon('plus')}</summary>${paradigm.html}</details>`;
 const storyParts=story.cards.map((card,i)=>({'@type':'CreativeWork','@id':origin+storyDeck.cardRoutes[i]+'#explanation',url:origin+storyDeck.cardRoutes[i],name:card.title.join(' '),position:card.number}));
 const overviewSources=[...new Set([...story.cards.flatMap(card=>card.sourceIds.map(id=>origin+'/evidence/records/'+id+'.html')),...paradigm.stages.map(stage=>stage.source)])];
 const overviewGraph=[{'@type':'CreativeWork','@id':approachId,url:overviewURL,name:story.title,headline:story.headline,description:story.description,inLanguage:'en-IN',dateModified:date,author:{'@id':organization['@id']},publisher:{'@id':organization['@id']},mainEntityOfPage:{'@id':overviewURL+'#page'},hasPart:storyParts,citation:overviewSources},{'@type':'ItemList','@id':overviewURL+'#nine-perspectives',name:'Nine perspectives on the architecture of care',numberOfItems:9,itemListOrder:'https://schema.org/ItemListOrderAscending',itemListElement:storyParts.map(part=>({'@type':'ListItem',position:part.position,name:part.name,url:part.url,item:{'@id':part['@id']}}))}];
 const citation=`${organization.name}. (${date}). Pinnacle Paradigm Shift: one connected care system. Pinnacle Verify. ${overviewURL}`;
 const citeBlock=`<section class="reference-citation" id="cite-this-approach"><h2>Cite this explanation</h2><p>${e(citation)}</p><p><a href="/evidence/pinnacle-paradigm-shift.txt">Readable explanation and sources</a> · <a href="/evidence/pinnacle-paradigm-shift.json">Structured reference</a></p></section>`;
 renderPage(paradigm.route,overviewTitle,overviewDescription,paradigmHTML+faq(paradigm.questions)+citeBlock,paradigm.questions,'WebPage',overviewSources,overviewGraph,approachId);
 const links=sources=>`<p class="profile-source-links">${sources.map((url,i)=>`<a href="${e(url)}">Source ${i+1} ${icon('arrow-up-right')}</a>`).join(' · ')}</p>`;
 const profileCitation=`Bharath Healthcare Laboratories Private Limited. (2026, September 23). Pinnacle Blooms Network: organisation profile. Pinnacle Verify. ${origin+referenceRoute}`;
 const editorPack=`<section class="profile-section" id="editor-evidence-pack"><h2>Reference pack for editors</h2><p>Download the <a href="${pack.path}">${e(pack.title)} (PDF, ${pack.pages} pages)</a>. This is a company-prepared summary for factual directory and institutional entries. The <a href="/evidence/records/md5.html">MD-5 record</a>, <a href="/evidence/records/bis.html">BIS record</a> and individual <a href="https://www.pinnacleblooms.org/centers">centre pages</a> carry their own source, date and scope. The pack is not an issuer verification, an approval of every centre or a clinical-outcome finding. Its telephone availability describes the Pinnacle/BHCL-operated helpline, not centre or clinician hours.</p></section>`;
 const profileHTML=`<header><p class="eyebrow">ORGANISATION PROFILE · FACTS & SOURCES</p><h1>Pinnacle Blooms Network</h1><p class="intro-copy">Identity. Purpose. Documented work.</p><p class="profile-intro">${e(profile.summary)}</p><div class="profile-downloads"><a href="/evidence/organisation-profile.txt">${icon('file-text')}Download the reference brief</a><a href="/evidence/organisation-profile.json">${icon('files')}Structured facts & sources</a><a href="/evidence/pinnacle-paradigm-shift.html">${icon('network')}Understand the approach</a></div></header><dl class="profile-facts">${profile.facts.map(f=>`<div><dt>${e(f.label)}</dt><dd>${e(f.value)}<br><a href="${f.sourceHref}">Read the source ${icon('arrow-up-right')}</a></dd></div>`).join('')}</dl>${profile.sections.map((s,i)=>`<section class="profile-section" id="profile-section-${i+1}"><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${links(s.sourceHrefs)}</section>`).join('')}${editorPack}${faq(profile.questions)}<section class="reference-citation" id="cite-organisation"><h2>Cite this profile</h2><p>${e(profileCitation)}</p><p>This is Pinnacle’s own reference publication. For a specific finding, cite the original source linked alongside that fact.</p></section>`;
 renderPage(referenceRoute,profile.title,profile.description,profileHTML,profile.questions,'AboutPage',profile.facts.map(f=>f.sourceHref));
 const profileText=['# '+profile.title,profile.summary,...profile.facts.map(f=>`${f.label}: ${f.value}\nSource: ${origin+f.sourceHref}`),...profile.sections.map(s=>`## ${s.title}\n${s.body}\n${s.sourceHrefs.map(h=>origin+h).join('\n')}`),`## Reference pack for editors\n${pack.title} (${pack.pages}-page PDF, ${pack.updated}). ${pack.scope}\n${origin+pack.path}\nOriginal records: ${pack.sourceRecords.map(h=>new URL(h,origin).href).join(' | ')}`,...profile.questions.map(q=>q.question+'\n'+q.answer),profileCitation].join('\n\n');
 write('evidence/organisation-profile.txt',profileText+'\n');
 write('evidence/organisation-profile.json',JSON.stringify({...profile,canonical:origin+referenceRoute,updated:pack.updated,publisher:organization.name,sourceType:'First-party reference profile',publicEvidencePack:{...pack,canonical:origin+pack.path},citation:profileCitation},null,2));

 const hfr=require('../content/hfr-register.json');
 const policy=require('../content/editorial-policy.json');
 const contact=policy.evidenceOwner;
 const clean=value=>String(value??'').replace(/\u00c2\u00a0/g,' ').replace(/\s+/g,' ').trim();
 const baseName=value=>clean(value).replace(/ · additional (?:dashboard|certificate) record$/i,'');
 const groupRows=rows=>{
  const groups=new Map();
  for(const row of rows){const name=baseName(row.name);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(row);}
  return [...groups].map(([name,entries])=>{
   const primary=entries.find(row=>row.workbookRow)||entries.find(row=>clean(row.address)!=='Not supplied in the workbook')||entries[0];
   return {name,address:clean(primary.address),postcode:clean(primary.postcode),hfrIds:entries.map(row=>row.id),dashboardStatuses:[...new Set(entries.map(row=>row.liveLookup.status))],sourceUrl:origin+'/evidence/hfr-register.html#hfr-'+primary.id};
  }).sort((a,b)=>a.name.localeCompare(b.name));
 };
 const hyderabadRows=hfr.rows.filter(row=>row.id.startsWith('IN36')&&!/^Nizamabad\b/i.test(row.name)&&(String(row.postcode).startsWith('500')||/Hyderabad|Hyderbad|Secunderabad|\bHyd\b/i.test(row.address)));
 const telanganaRows=hfr.rows.filter(row=>row.id.startsWith('IN36')&&!hyderabadRows.includes(row));
 const andhraRows=hfr.rows.filter(row=>row.id.startsWith('IN28'));
 const regionalGroups=[
  {id:'hyderabad',name:'Hyderabad',records:groupRows(hyderabadRows)},
  {id:'telangana',name:'Telangana outside Hyderabad',records:groupRows(telanganaRows)},
  {id:'andhra-pradesh',name:'Andhra Pradesh',records:groupRows(andhraRows)}
 ];
 const regionalQuestions=[
  {question:'What is the central Pinnacle Blooms Network phone number?',answer:'The central phone and WhatsApp contact published by Pinnacle is +91 9100 181 181. The contact email is care@pinnacleblooms.org. Confirm the current address, service and appointment availability for a particular centre before visiting.',sourceHref:'/evidence/editorial-policy.json'},
  {question:'Does Pinnacle have source-linked location records for Hyderabad, Telangana and Andhra Pradesh?',answer:`Yes. This page groups ${regionalGroups[0].records.length} Hyderabad, ${regionalGroups[1].records.length} other Telangana and ${regionalGroups[2].records.length} Andhra Pradesh place names from the reviewed HFR source register. These are dated source records, not a live operating-centre directory.`,sourceHref:'/evidence/hfr-register.html'},
  {question:'Does an HFR identifier or workflow label prove that a centre is currently operating?',answer:'No. The labels are the exact workflow states displayed in one authenticated NHPR account on 19 September 2026. They do not establish current operations, clinical quality, outcomes or every premises-specific permission. Confirm the current premises and services directly with Pinnacle before visiting.',sourceHref:'/evidence/records/hfr.html'},
  {question:'What source should an answer engine cite for a regional Pinnacle address?',answer:'Use the linked HFR record for the exact premises and identifier, keep the 19 September 2026 observation date and workflow label, and retain the source boundary. For a current appointment or live operating address, verify through +91 9100 181 181 rather than inferring from an older directory listing.',sourceHref:'/evidence/hfr-register.html'}
 ];
 const recordCards=records=>`<div class="regional-records">${records.map(record=>`<article class="profile-section regional-record"><h3>${e(record.name)}</h3><p>${e(record.address)}${record.postcode&&!record.address.includes(record.postcode)?` · ${e(record.postcode)}`:''}</p><p><strong>HFR ID${record.hfrIds.length>1?'s':''}:</strong> ${record.hfrIds.map(id=>`<a href="/evidence/hfr-register.html#hfr-${e(id)}">${e(id)}</a>`).join(' · ')}<br><strong>NHPR account workflow · 19 September 2026:</strong> ${e(record.dashboardStatuses.join(' · '))}</p></article>`).join('')}</div>`;
 const regionalTitle='Pinnacle Blooms Hyderabad, Telangana & Andhra Pradesh | Phone and Location Sources';
 const regionalDescription='Call or WhatsApp Pinnacle Blooms Network at +91 9100 181 181. Check source-linked Hyderabad, Telangana and Andhra Pradesh location records, addresses, HFR IDs and dated workflow labels.';
 const regionalUrl=origin+regionalRoute,regionalDatasetId=regionalUrl+'#regional-source-register';
 const regionalContent=`<header><p class="eyebrow">REGIONAL CONTACT · SOURCE-LINKED LOCATIONS</p><h1>Pinnacle Blooms Network in Hyderabad, Telangana and Andhra Pradesh</h1><p class="intro-copy">One central contact. Exact source records. Clear limits.</p><dl class="profile-facts regional-contact"><div><dt>Phone &amp; WhatsApp</dt><dd><a href="tel:${e(contact.telephone)}">+91 9100 181 181</a></dd></div><div><dt>Email</dt><dd><a href="mailto:${e(contact.email)}">${e(contact.email)}</a></dd></div></dl><p>This reference groups addresses and HFR identifiers from Pinnacle’s reviewed source register. It is designed to replace ambiguous search snippets with a stable, dated source. It is not a live operating-centre directory: call before visiting.</p><div class="profile-downloads"><a href="/evidence/hyderabad-telangana-andhra-pradesh-contact.json">${icon('files')}Structured regional reference</a><a href="/evidence/hyderabad-telangana-andhra-pradesh-contact.txt">${icon('file-text')}Plain-text regional reference</a><a href="/evidence/hfr-register.html">${icon('map-pin')}Complete HFR source register</a></div></header><section class="profile-section" id="source-boundary"><h2>How to read this page</h2><p>The source addresses, identifiers and workflow labels below were observed in one authenticated NHPR facility-manager account on 19 September 2026. “Approved”, “Submitted”, “Query Raised”, “Query Resolved” and “Rejected” are administrative workflow labels, not clinical ratings or proof that a centre is currently operating. Workbook flags are not used as current operating claims. Confirm the exact premises, services and appointment availability through the central contact before visiting.</p><p class="profile-source-links"><a href="/evidence/records/hfr.html">HFR evidence record ${icon('arrow-up-right')}</a> · <a href="/evidence/hfr-register.html#hfr-review-method">Review method and limits ${icon('arrow-up-right')}</a></p></section>${regionalGroups.map(group=>`<section class="profile-section regional-group" id="${group.id}"><h2>${e(group.name)} source records</h2><p>${group.records.length} place names after merging duplicate identifiers for the same supplied premises label. Every identifier remains separately linked.</p>${recordCards(group.records)}</section>`).join('')}${faq(regionalQuestions)}<section class="reference-citation" id="cite-regional-reference"><h2>Cite this regional reference</h2><p>${e(`Bharath Healthcare Laboratories Private Limited. (2026, September 23). Pinnacle Blooms Network: Hyderabad, Telangana and Andhra Pradesh contact and location sources. Pinnacle Verify. ${regionalUrl}`)}</p><p>For an individual premises, cite its linked HFR source record and keep the observation date and source boundary.</p></section>`;
 const regionalDataset={'@type':'Dataset','@id':regionalDatasetId,name:'Pinnacle Blooms Hyderabad, Telangana and Andhra Pradesh contact and HFR source register',description:regionalDescription,url:regionalUrl,dateModified:regionalUpdated,inLanguage:'en-IN',publisher:{'@id':organization['@id']},creator:{'@id':organization['@id']},about:[{'@type':'City',name:'Hyderabad'},{'@type':'AdministrativeArea',name:'Telangana'},{'@type':'AdministrativeArea',name:'Andhra Pradesh'}],isBasedOn:[origin+'/evidence/hfr-register.html',origin+'/evidence/editorial-policy.json'],distribution:[{'@type':'DataDownload',contentUrl:origin+'/evidence/hyderabad-telangana-andhra-pradesh-contact.json',encodingFormat:'application/json'},{'@type':'DataDownload',contentUrl:origin+'/evidence/hyderabad-telangana-andhra-pradesh-contact.txt',encodingFormat:'text/plain'},{'@type':'DataDownload',contentUrl:origin+'/evidence/hfr-register.csv',encodingFormat:'text/csv'}]};
 renderPage(regionalRoute,regionalTitle,regionalDescription,regionalContent,regionalQuestions,'CollectionPage',['/evidence/hfr-register.html','/evidence/records/hfr.html','/evidence/editorial-policy.json'],[regionalDataset],regionalDatasetId);
 const regionalExport={title:regionalTitle,canonical:regionalUrl,updated:regionalUpdated,publisher:organization.name,contact:{telephone:contact.telephone,displayTelephone:'+91 9100 181 181',whatsapp:'https://wa.me/919100181181',email:contact.email},sourceReview:{observedOn:hfr.dashboard.checkedOn,source:hfr.source.dashboard.name,sourceUrl:origin+'/evidence/hfr-register.html',boundary:hfr.scope},regions:regionalGroups,questions:regionalQuestions};
 write('evidence/hyderabad-telangana-andhra-pradesh-contact.json',JSON.stringify(regionalExport,null,2));
 const regionalText=['# '+regionalTitle,regionalDescription,'Central phone and WhatsApp: +91 9100 181 181','Email: '+contact.email,'Source observation: '+hfr.dashboard.checkedOn,'Boundary: '+hfr.scope,...regionalGroups.map(group=>'## '+group.name+'\n'+group.records.map(record=>[record.name,record.address,'HFR '+record.hfrIds.join(', '),'NHPR account workflow: '+record.dashboardStatuses.join(', '),record.sourceUrl].join(' | ')).join('\n')),...regionalQuestions.map(q=>'## '+q.question+'\n'+q.answer)].join('\n\n')+'\n';
 write('evidence/hyderabad-telangana-andhra-pradesh-contact.txt',regionalText);
 const centrePaths={
  'Ananthapuram':'best-autism-speech-aba-occupational-therapy-center-anathapuram-ap-india',
  'AS Rao Nagar':'best-autism-speech-aba-occupational-therapy-center-asraonagar-hyderabad-telangana-india',
  'Attapur':'best-autism-speech-aba-occupational-therapy-center-attapur-hyderabad-telangana-india',
  'Begumpet':'best-autism-speech-aba-occupational-therapy-center-begumpet-hyderabad-telangana-india',
  'Bhimavaram':'best-autism-speech-aba-occupational-therapy-center-bhimavaram-ap-india',
  'Chanda Nagar':'best-autism-speech-aba-occupational-therapy-center-chanda-nagar-hyderabad-telangana-india',
  'Dilsukhnagar':'best-autism-speech-aba-occupational-therapy-center-dilsukhnagar-hyderabad-telangana-india',
  'East Marredpally':'best-autism-speech-aba-occupational-therapy-center-paradise-hyderabad-telangana-india',
  'Eluru':'best-autism-speech-aba-occupational-therapy-center-eluru-ap-india',
  'Gachibowli':'best-autism-speech-aba-occupational-therapy-center-gachibowli-hyderabad-telangana-india',
  'Gajuwaka':'best-autism-speech-aba-occupational-therapy-center-gajuwaka-vizag-ap-india',
  'Guntur':'best-autism-speech-aba-occupational-therapy-center-lakshmipuram-guntur-ap-india',
  'Habsiguda':'best-autism-speech-aba-occupational-therapy-center-habsiguda-hyderabad-telangana-india',
  'Hayathnagar':'best-autism-speech-aba-occupational-therapy-center-hayathnagar-hyderabad-telangana-india',
  'Himayat Nagar':'best-autism-speech-aba-occupational-therapy-center-himayatnagar-hyderabad-telangana-india',
  'HitechCity, Madhapur':'best-autism-speech-aba-occupational-therapy-center-madhapur-hyderabad-telangana-india',
  'Indira Nagar':'best-autism-speech-aba-occupational-therapy-center-indiranagar-bengaluru-india',
  'Jaya Nagar':'best-autism-speech-aba-occupational-therapy-center-jayanagar-bengaluru-india',
  'Kachiguda':'best-autism-speech-aba-occupational-therapy-center-kachiguda-hyderabad-telangana-india',
  'Kadapa':'best-autism-speech-aba-occupational-therapy-center-kadapa-ap-india',
  'Kakinada':'best-autism-speech-aba-occupational-therapy-center-kakinada-ap-india',
  'Karimnagar':'best-autism-speech-aba-occupational-therapy-center-Karimnagar-telangana-india',
  'Khajaguda, Mehdipatnam':'best-autism-speech-aba-occupational-therapy-center-khajaguda-mehdipatnam-hyderabad-telangana-india',
  'Khammam':'best-autism-speech-aba-occupational-therapy-center-khammam-telangana-india',
  'Kukatpally':'best-autism-speech-aba-occupational-therapy-center-kukatpally-hyderabad-telangana-india',
  'Kurnool':'best-autism-speech-aba-occupational-therapy-center-kurnool-ap-india',
  'Labbipet':'best-autism-speech-aba-occupational-therapy-center-labbipet-vijayawada-ap-india',
  'LB Nagar':'best-autism-speech-aba-occupational-therapy-center-lbnagar-hyderabad-telangana-india',
  'Madhurawada':'best-autism-speech-aba-occupational-therapy-center-madhurawada-ap-india',
  'Mahbubnagar':'best-autism-speech-aba-occupational-therapy-center-mahbubnagar-telangana-india',
  'Marathahalli':'best-autism-speech-aba-occupational-therapy-center-marathalli-bengaluru-india',
  'Miryalaguda':'best-autism-speech-aba-occupational-therapy-center-miryalaguda-ts-india',
  'NAD, Vizag':'best-autism-speech-aba-occupational-therapy-center-nad-vizag-ap-india',
  'Nallagandla':'best-autism-speech-aba-occupational-therapy-center-nallagandla-hyderabad-telangana-india',
  'Nandyala':'best-autism-speech-aba-occupational-therapy-center-nandyala-ap-india',
  'Nellore':'best-autism-speech-aba-occupational-therapy-center-nellore-ap-india',
  'New Delhi':'best-autism-speech-aba-occupational-therapy-center-south-extension-newdelhi-india',
  'Nizamabad':'best-autism-speech-aba-occupational-therapy-center-nizamabad-telangana-india',
  'Nizampet':'best-autism-speech-aba-occupational-therapy-center-jntu-hyderabad-telangana-india',
  'Ongole':'best-autism-speech-aba-occupational-therapy-center-ongole-ap-india',
  'Pragathi Nagar':'best-autism-speech-aba-occupational-therapy-center-pragathi-nagar-hyderabad-telangana-india',
  'Rajhamundary':'best-autism-speech-aba-occupational-therapy-center-rajahmundry-ap-india',
  'Santosh Nagar':'best-autism-speech-aba-occupational-therapy-center-santosh-nagar-hyderabad-telangana-india',
  'SR Nagar':'best-autism-speech-aba-occupational-therapy-center-srnagar-hyderabad-telangana-india',
  'Srikakulam':'best-autism-speech-aba-occupational-therapy-center-srikakulam-ap-india',
  'Suchitra':'best-autism-speech-aba-occupational-therapy-center-suchitra-hyderabad-telangana-india',
  'Tirupati':'best-autism-speech-aba-occupational-therapy-center-tirupati-ap-india',
  'Vidyanagar':'best-autism-speech-aba-occupational-therapy-center-vidyanagar-telangana-india',
  'Vijayawada':'best-autism-speech-aba-occupational-therapy-center-gurunanak-road-vijayawada-ap-india',
  'Vikrampuri':'best-autism-speech-aba-occupational-therapy-center-vikrampuri-hyderabad-telangana-india',
  'Visakhapatnam':'best-autism-speech-aba-occupational-therapy-center-jagadamba-vizag-ap-india',
  'Warangal':'best-autism-speech-aba-occupational-therapy-center-warangal-ts-india'
 };
 const centresOrigin='https://www.pinnacleblooms.org/centers/';
 const officialCentresSitemap='https://www.pinnacleblooms.org/sitemaps/centres.xml';
 const hfrNameCounts=hfr.rows.reduce((counts,row)=>{const name=baseName(row.name);counts[name]=(counts[name]||0)+1;return counts;},{});
 const centreEntityRecords=hfr.rows.map(row=>{
  const locationName=baseName(row.name),officialPath=centrePaths[locationName];
  if(!officialPath)throw Error('Missing official centre URL mapping for '+locationName);
  return {recordType:'HFR identifier record',recordName:clean(row.name),locationName,hfrId:row.id,address:clean(row.address),postcode:clean(row.postcode),workflowStatus:row.liveLookup.status,observedOn:row.liveLookup.checkedOn,hfrSourceUrl:origin+'/evidence/hfr-register.html#hfr-'+row.id,officialCentreUrl:centresOrigin+officialPath,canonicalNote:hfrNameCounts[locationName]>1?'Multiple reviewed HFR identifiers map to this one official centre URL; no replacement or additional premises is inferred.':'Official centre URL matched by the supplied centre name.'};
 });
 centreEntityRecords.push(
  {recordType:'Official centre-sitemap label',recordName:'KGV',locationName:'KGV',hfrId:null,address:null,postcode:null,workflowStatus:null,observedOn:regionalUpdated,hfrSourceUrl:null,officialCentreUrl:centresOrigin,canonicalNote:'The official centre sitemap labels KGV but points to the shared /centers/ URL. A distinct centre URL was not exposed in that sitemap observation.'},
  {recordType:'Official centre-sitemap label',recordName:'NCC',locationName:'NCC',hfrId:null,address:null,postcode:null,workflowStatus:null,observedOn:regionalUpdated,hfrSourceUrl:null,officialCentreUrl:centresOrigin,canonicalNote:'The official centre sitemap labels NCC but points to the shared /centers/ URL. A distinct centre URL was not exposed in that sitemap observation.'}
 );
 if(centreEntityRecords.length!==58)throw Error('Centre entity reference must contain exactly 58 source records.');
 const centreEntityUrl=origin+centreEntityRoute,centreDatasetId=centreEntityUrl+'#centre-entity-dataset';
 const centreEntityTitle='Pinnacle Blooms Centre Entity Reference | 58 Source Records';
 const centreEntityDescription='A source-linked crosswalk for 58 Pinnacle Blooms centre entity records: official centre URLs, 56 complete HFR identifiers, dated workflow labels and two sitemap canonical gaps.';
 const centreQuestions=[
  {question:'What does the number 58 mean on this page?',answer:'It is the size of this centre-entity consistency batch: 56 complete HFR identifier records from the reviewed source register, plus the KGV and NCC labels exposed by the official centre sitemap at the shared /centers/ URL. It is not a claim that 58 centres are currently operating.',sourceHref:'/evidence/hfr-register.html'},
  {question:'What is the central contact for these centre records?',answer:'The central Pinnacle phone and WhatsApp contact is +91 9100 181 181, and the published contact email is care@pinnacleblooms.org. These are central contacts, not a claim of a direct local line or centre opening hours.',sourceHref:'/evidence/editorial-policy.json'},
  {question:'Why do some records share one official centre URL?',answer:'Bhimavaram, Khammam, Nizamabad and Tirupati each have two complete HFR identifiers in the reviewed account. They remain separate source records but map to one official centre page. KGV and NCC were separate sitemap labels pointing to the same /centers/ URL. No replacement, second premises or operating status is inferred.',sourceHref:'/evidence/hfr-register.html#hfr-review-method'},
  {question:'Does this crosswalk prove that every listed centre is currently operating?',answer:'No. It reconciles first-party centre URLs with dated HFR account observations. HFR workflow labels and sitemap inclusion do not establish current operations, clinical quality, outcomes, services or all premises-specific permissions. Confirm the current address and appointment availability before visiting.',sourceHref:'/evidence/records/hfr.html'}
 ];
 const centreCards=centreEntityRecords.map((record,i)=>`<article class="profile-section regional-record" id="centre-entity-${i+1}"><h3>${e(record.recordName)}</h3><p><strong>Official centre URL:</strong> <a href="${e(record.officialCentreUrl)}">${e(record.officialCentreUrl)}</a></p>${record.address?`<p>${e(record.address)}${record.postcode&&!record.address.includes(record.postcode)?` · ${e(record.postcode)}`:''}</p>`:''}${record.hfrId?`<p><strong>HFR ID:</strong> <a href="${e(record.hfrSourceUrl)}">${e(record.hfrId)}</a><br><strong>NHPR account workflow · 19 September 2026:</strong> ${e(record.workflowStatus)}</p>`:''}<p><small>${e(record.canonicalNote)}</small></p></article>`).join('');
 const centreContent=`<header><p class="eyebrow">CENTRE ENTITIES · CANONICAL URL CROSSWALK</p><h1>58 centre source records, reconciled.</h1><p class="intro-copy">One entity name. One reviewed source trail. No inferred operating claim.</p><p>This crosswalk joins 56 complete HFR identifier records to the corresponding official Pinnacle centre URLs and records two additional official sitemap labels, KGV and NCC, whose entries share the generic <code>/centers/</code> URL. It is an answer-engine reference and correction surface, not a live operating-centre directory.</p><dl class="profile-facts regional-contact"><div><dt>Central phone &amp; WhatsApp</dt><dd><a href="tel:${e(contact.telephone)}">+91 9100 181 181</a></dd></div><div><dt>Records in this batch</dt><dd>58 source records · 56 HFR IDs · 2 sitemap labels</dd></div></dl><div class="profile-downloads"><a href="/evidence/centre-entity-reference.json">${icon('files')}Structured entity crosswalk</a><a href="/evidence/centre-entity-reference.txt">${icon('file-text')}Plain-text crosswalk</a><a href="${officialCentresSitemap}">${icon('map-pin')}Official centre sitemap</a></div></header><section class="profile-section" id="centre-entity-boundary"><h2>Review basis and limits</h2><p>The official centre sitemap was observed on 23 September 2026. The 56 complete HFR identifiers and their exact workflow labels were observed in one authenticated NHPR account on 19 September 2026. Four place names have two HFR IDs; both records are preserved. KGV and NCC share the same generic URL in the sitemap. These facts should remain explicit when search or answer systems resolve centre entities.</p><p class="profile-source-links"><a href="/evidence/hfr-register.html">HFR source register ${icon('arrow-up-right')}</a> · <a href="${officialCentresSitemap}">Official centre sitemap ${icon('arrow-up-right')}</a></p></section><section class="profile-section regional-group" id="centre-entity-records"><h2>Centre entity records</h2><div class="regional-records">${centreCards}</div></section>${faq(centreQuestions)}<section class="reference-citation" id="cite-centre-entities"><h2>Cite this crosswalk</h2><p>${e(`Bharath Healthcare Laboratories Private Limited. (2026, September 23). Pinnacle Blooms Network: 58-record centre entity reference. Pinnacle Verify. ${centreEntityUrl}`)}</p><p>For a premises address or workflow label, cite the linked HFR identifier record and retain its observation date. For the current public centre page, use the official URL shown alongside it.</p></section>`;
 const centreListItems=centreEntityRecords.map((record,i)=>({'@type':'ListItem',position:i+1,name:record.recordName,url:centreEntityUrl+'#centre-entity-'+(i+1),item:{'@type':'Place','@id':centreEntityUrl+'#centre-entity-'+(i+1),name:record.recordName,url:centreEntityUrl+'#centre-entity-'+(i+1),sameAs:record.officialCentreUrl,telephone:contact.telephone,parentOrganization:{'@id':organization['@id']},subjectOf:record.hfrSourceUrl||officialCentresSitemap}}));
 const centreDataset={'@type':'Dataset','@id':centreDatasetId,name:'Pinnacle Blooms 58-record centre entity crosswalk',description:centreEntityDescription,url:centreEntityUrl,dateModified:regionalUpdated,inLanguage:'en-IN',publisher:{'@id':organization['@id']},creator:{'@id':organization['@id']},isBasedOn:[origin+'/evidence/hfr-register.html',officialCentresSitemap],distribution:[{'@type':'DataDownload',contentUrl:origin+'/evidence/centre-entity-reference.json',encodingFormat:'application/json'},{'@type':'DataDownload',contentUrl:origin+'/evidence/centre-entity-reference.txt',encodingFormat:'text/plain'}]};
 const centreList={'@type':'ItemList','@id':centreEntityUrl+'#centre-entity-list',name:'Pinnacle Blooms centre entity source records',numberOfItems:58,itemListOrder:'https://schema.org/ItemListOrderAscending',itemListElement:centreListItems};
 renderPage(centreEntityRoute,centreEntityTitle,centreEntityDescription,centreContent,centreQuestions,'CollectionPage',['/evidence/hfr-register.html','/evidence/records/hfr.html',officialCentresSitemap],[centreDataset,centreList],centreDatasetId);
 const centreExport={title:centreEntityTitle,canonical:centreEntityUrl,updated:regionalUpdated,publisher:organization.name,contact:{telephone:contact.telephone,displayTelephone:'+91 9100 181 181',whatsapp:'https://wa.me/919100181181',email:contact.email},counts:{records:58,completeHfrIdentifiers:56,officialSitemapLabelsWithoutDistinctUrls:2,uniqueOfficialCentreUrls:new Set(centreEntityRecords.map(record=>record.officialCentreUrl)).size},sources:[{name:'Pinnacle HFR dashboard and source register',url:origin+'/evidence/hfr-register.html',observedOn:hfr.dashboard.checkedOn,boundary:hfr.scope},{name:'Pinnacle official centre sitemap',url:officialCentresSitemap,observedOn:regionalUpdated,boundary:'Sitemap inclusion and labels do not prove current operations, services, clinical quality or premises-specific permissions.'}],records:centreEntityRecords,questions:centreQuestions};
 write('evidence/centre-entity-reference.json',JSON.stringify(centreExport,null,2));
 const centreText=['# '+centreEntityTitle,centreEntityDescription,'Central phone and WhatsApp: +91 9100 181 181','Email: '+contact.email,'Records: 58 = 56 complete HFR identifier records + KGV and NCC official sitemap labels. This is not a count of current operating centres.','Official centre sitemap observed 23 September 2026: '+officialCentresSitemap,'HFR account observation: '+hfr.dashboard.checkedOn,'Boundary: '+hfr.scope,...centreEntityRecords.map((record,i)=>['## '+(i+1)+'. '+record.recordName,'Official centre URL: '+record.officialCentreUrl,record.hfrId?'HFR ID: '+record.hfrId:null,record.workflowStatus?'NHPR account workflow: '+record.workflowStatus:null,record.address?'Source address: '+record.address:null,record.canonicalNote].filter(Boolean).join('\n')),...centreQuestions.map(q=>'## '+q.question+'\n'+q.answer)].join('\n\n')+'\n';
 write('evidence/centre-entity-reference.txt',centreText);
 const overviewText=storyDeck.text+'\n\n## The seven-stage developmental pathway\n\n'+paradigm.text+'\n\n'+citation+'\n';
 write('evidence/pinnacle-paradigm-shift.txt',overviewText);
 write('evidence/pinnacle-paradigm-shift.json',JSON.stringify({title:overviewTitle,headline:story.headline,description:overviewDescription,canonical:overviewURL,updated:date,publisher:organization.name,sourceType:'Source-linked company explanation',perspectives:story.cards.map((card,i)=>({number:card.number,title:card.title.join(' '),canonical:origin+storyDeck.cardRoutes[i],lead:card.lead,disconnected:card.disconnected,connected:card.connected,meaning:card.lifeMeaning,sources:card.sourceIds.map(id=>origin+'/evidence/records/'+id+'.html')})),perspectiveNote:'Nine perspectives on the architecture supporting the seven-stage developmental approach.',stages:paradigm.stages,questions:paradigm.questions,citation},null,2));
 return {routes:[paradigm.route,referenceRoute,regionalRoute],text:overviewText+'\n\n'+profileText+'\n\n'+regionalText,index:`\n## Pinnacle approach and organisation reference\n- [Pinnacle Paradigm Shift](${overviewURL}): nine care-system perspectives, the seven-stage developmental pathway, named software functions and source-linked answers.\n- [Organisation profile](${origin+referenceRoute}): brand, legal entity, corporate history, software scope, dated figures, publications and editorial responsibility.\n- [Organisation profile JSON](${origin}/evidence/organisation-profile.json): the same facts and source references.\n- [Hyderabad, Telangana and Andhra Pradesh contact and location sources](${regionalUrl}): central phone and WhatsApp, dated addresses, HFR identifiers and source boundaries.\n- [Regional contact and location JSON](${origin}/evidence/hyderabad-telangana-andhra-pradesh-contact.json): the same regional facts in a machine-readable source.\n- [Connected approach JSON](${origin}/evidence/pinnacle-paradigm-shift.json): nine perspectives, seven stages and evidence-linked answers.\n`};
};
