'use strict';
const data=require('../content/how-pinnacleai-works.json');
module.exports=({e,icon,origin})=>{
 const source=s=>`<a class="source-link" href="/evidence/records/${s.record}.html">${icon('file-search')}${e(s.label)}</a>`;
 const reports=data.reportPack;
 const reportHTML=`<details class="context-disclosure" id="child-report-pack"><summary>What do the child’s reports explain? ${icon('plus')}</summary><h4>${e(reports.title)}</h4><p>${e(reports.intro)}</p><ul class="workflow-report-list">${reports.reports.map(r=>`<li>${icon('files')}<span><strong>${e(r.name)}</strong><span>${e(r.meaning)}</span></span></li>`).join('')}</ul><p>${e(reports.interpretation)}</p><p class="workflow-note">${e(reports.review)}</p><p>${e(reports.privacy)}</p></details>`;
 const html=`<article class="workflow-explainer" id="how-pinnacleai-works" aria-labelledby="workflow-title"><p class="eyebrow">HOW PINNACLEAI® WORKS</p><h3 id="workflow-title">${e(data.title)}</h3><p class="workflow-intro">${e(data.intro)}</p><ol class="workflow-modules" aria-label="Connected measurement, planning, practice and review">${data.modules.map((m,i)=>`<li><span class="workflow-marker" aria-hidden="true">${icon(m.icon)}</span><span class="workflow-step">0${i+1} · ${e(m.verb)}</span><h4>${e(m.name)}</h4><p>${e(m.text)}</p></li>`).join('')}</ol><p class="workflow-continuity">${icon('rotate-ccw')}<span>${e(data.continuity)}</span></p><p class="workflow-detail-label">Explore the part that matters to you</p><div class="workflow-questions">${reportHTML}${data.details.map(d=>`<details class="context-disclosure" id="${d.id}"><summary>${e(d.question)} ${icon('plus')}</summary><p>${e(d.answer)}</p><p class="workflow-note">${e(d.note)}</p><div class="workflow-sources">${d.sources.map(source).join('')}</div></details>`).join('')}</div><p class="workflow-scope">${e(data.scope)}</p><nav class="workflow-evidence" aria-label="Evidence for the PinnacleAI workflow">${source({record:'md5',label:'Licensed intended use'})}${source({record:'bis',label:'Named software modules'})}<a class="source-link" href="/evidence/research-library.html">${icon('files')}Methods, studies and research status</a></nav><details class="context-disclosure workflow-version" id="workflow-document-versions"><summary>Document versions and measurement detail ${icon('plus')}</summary><p>${e(data.versionNote)}</p>${source({record:'methodology',label:'Methodology preprint · page 3'})}${source({record:'sovereign-walkthrough',label:'Company walkthrough · page 35'})}</details></article>`;
 const text='## How PinnacleAI® works\n\n'+data.title+'\n'+data.intro+'\n\n'+data.modules.map((m,i)=>`${i+1}. ${m.verb} — ${m.name}\n${m.text}\nSource: ${origin}/evidence/records/${m.record}.html`).join('\n\n')+'\n\n'+data.continuity+'\n\n'+data.details.map(d=>d.question+'\n'+d.answer+'\n'+d.note+'\n'+d.sources.map(s=>`${s.label}: ${origin}/evidence/records/${s.record}.html`).join('\n')).join('\n\n')+'\n\n'+data.scope+'\n'+data.versionNote+'\n';
 return {data,html,text:text+'\n'+reports.title+'\n'+reports.intro+'\n'+reports.reports.map(r=>r.name+': '+r.meaning).join('\n')+'\n'+reports.interpretation+'\n'+reports.review+'\n'+reports.privacy+'\n'};
};
