import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const baseline=path.resolve(process.argv[2]);
const output=path.resolve(process.argv[3]);
let source=await fs.readFile(path.join(baseline,'index.js'),'utf8');
const before=crypto.createHash('sha256').update(source).digest('hex');
if(before!=='9ce464e38cbaff0bed7c3eea93db12e9d431fcc84ce22e0c5bca866a64ead1f2')throw Error('Unexpected baseline; inspect latest production before patching');
function replaceOnce(old,value){if(source.split(old).length!==2)throw Error('Patch target not unique: '+old.slice(0,90));source=source.replace(old,value);}
replaceOnce('function searchPage(ctx) {',(await fs.readFile(path.join(dir,'search-page.js'),'utf8'))+'\nfunction searchPage(ctx) {');
replaceOnce('else if (R.kind === "search") built = searchPage(ctx);','else if (R.kind === "search") return searchResultsResponse(ctx, url);');
replaceOnce('async function withWebsiteCallTag(response) {','async function withWebsiteCallTag(response) {\n  if (response.headers.get("x-pinnacle-private-search") === "1") return response;');
replaceOnce('?__ask_html=20260923-helpline-links','?__ask_html=20261003-search-citations');
replaceOnce('<style>${CSS}</style>','<style>${CSS}\n@media(max-width:600px){.mast-top{flex-wrap:wrap;gap:10px}.navpills{flex-wrap:wrap;min-width:0;max-width:100%}.fgrid21{grid-template-columns:repeat(2,minmax(0,1fr))}.fblk{min-width:0;overflow-wrap:anywhere}}</style>');
replaceOnce('The answer exists in the Ko\\u015Ba \\u2014 this particular view is still being prepared. Search, or return to the front door.','We could not find a published answer at this address. <a href="${BASE}/search">Search the published answers</a> or <a href="${BASE}">browse Ask Pinnacle</a>.');
await fs.mkdir(output,{recursive:true});
await fs.writeFile(path.join(output,'index.js'),source);
const modules=JSON.parse(await fs.readFile(path.join(baseline,'modules.json'),'utf8'));
for(const m of modules)if(m.file!=='index.js')await fs.copyFile(path.join(baseline,m.file),path.join(output,m.file));
await fs.writeFile(path.join(output,'modules.json'),JSON.stringify(modules,null,2));
console.log(JSON.stringify({baseline:before,patched:crypto.createHash('sha256').update(source).digest('hex'),files:modules.map(m=>m.file)}));
