import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const source=await fs.readFile(new URL('./search-page.js',import.meta.url),'utf8');
let calls=0, mode='ok', payload;
const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const sandbox={Response,URL,esc:escape,attr:escape,checkedAskJson:async(env,path,args)=>{calls++;payload=args;if(mode==='error')throw Error('DB error');if(mode==='empty')return {results:[]};return {results:[{slug:'speech-delay',title:'Speech & development',summary:'Published guidance',lang:'en'},{slug:'javascript:alert(1)',title:'Invalid path'}]};},html:(body,live,status)=>new Response(body,{status}),shell:ctx=>'<meta name="robots" content="noindex, nofollow">'+ctx.main};
vm.createContext(sandbox);vm.runInContext(source+'\nthis.run=searchResultsResponse;',sandbox);
const ctx=()=>({env:{CANONICAL_ORIGIN:'https://pinnacleblooms.org',ASK_BASE:'/ask'}});
let response=await sandbox.run(ctx(),new URL('https://pinnacleblooms.org/ask/search?q=speech+delay'));
let body=await response.text();assert.equal(response.status,200);assert.match(body,/Read the answer/);assert.match(body,/href="https:\/\/pinnacleblooms.org\/ask\/speech-delay"/);assert.doesNotMatch(body,/javascript:/);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal(response.headers.get('x-robots-tag'),'noindex, follow');assert.equal(response.headers.get('referrer-policy'),'no-referrer');
const callCount=calls;response=await sandbox.run(ctx(),new URL('https://pinnacleblooms.org/ask/search?q='));assert.equal(calls,callCount);assert.match(await response.text(),/at least two characters/);
assert.match(body,/<meta name="robots" content="noindex, follow">/);
mode='empty';response=await sandbox.run(ctx(),new URL('https://pinnacleblooms.org/ask/search?q='+encodeURIComponent('<script>alert("x")</script>')));body=await response.text();assert.doesNotMatch(body,/<script>/);assert.match(body,/&lt;script&gt;/);assert.match(body,/No published answers matched/);
mode='error';response=await sandbox.run(ctx(),new URL('https://pinnacleblooms.org/ask/search?q=speech'));assert.equal(response.status,503);assert.equal(response.headers.get('retry-after'),'60');assert.match(await response.text(),/temporarily unavailable/);
mode='ok';await sandbox.run(ctx(),new URL('https://pinnacleblooms.org/ask/search?q='+'x'.repeat(500)));assert.equal(payload.p_q.length,200);
console.log('PASS: results, canonical links, invalid paths, escaping, empty input/results, bounded query, outage status, no-store and crawler/referrer controls.');
