'use strict';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base='https://www.pinnacleblooms.org/verify/';
const data={
 title:'The outcome belongs at the beginning.',
 purpose:'A self-sufficient, mainstream life for your child.',
 history:{title:'160 Years Without a Unified Metric',author:'Pinnacle’s AbilityScore® monograph',url:'https://doi.org/10.5281/zenodo.19482123',thesis:'A history of measuring separate developmental dimensions raises a larger question: how do the findings guide the child’s whole life?',gap:'A technique can improve a task while its contribution to everyday participation remains unclear. Pinnacle challenges making the method the starting point and leaving the life question until later.'},
 independentContext:{organization:'WHO and UNICEF',year:2023,text:'The global report identifies unmet needs, fragmented and underfunded systems, waiting lists and exclusion. It calls for people-centred services and support for caregivers.',url:'https://www.who.int/news/item/15-09-2023-new-reports-highlights-neglected-health-needs-of-children-with-developmental-disabilities'},
 milestones:[
  {year:2001,title:'Functioning becomes an international reference',text:'WHO Member States endorse ICF, a framework addressing functioning, disability and environmental context.',url:'https://www.who.int/classifications/international-classification-of-functioning-disability-and-health'},
  {year:2006,title:'Independence and inclusion are explicit rights',text:'The UN adopts the CRPD. Article 26 connects habilitation and rehabilitation with independence, inclusion and participation.',url:'https://treaties.un.org/Pages/ViewDetails.aspx?chapter=4&mtdsg_no=IV-15&src=IND'},
  {year:2023,title:'The delivery gap remains',text:'WHO and UNICEF report fragmented systems and unmet needs, and call for people-centred services and caregiver support.',url:'https://www.who.int/news/item/15-09-2023-new-reports-highlights-neglected-health-needs-of-children-with-developmental-disabilities'}
 ],
 comparisonScope:'Two orders of decision-making. They explain the approach Pinnacle challenges and the approach it intends to implement; provider practices vary.',
 methodFirst:['Choose a method or speciality','Set exercises within that method','Record performance on those tasks','Ask what it adds up to in the child’s life'],
 lifeFirst:['Name the child’s meaningful life priorities','Understand the abilities and support they require','Set observable goals; select the methods and people','Review everyday use; adapt the work to the child'],
 examples:[{task:'Holding a pencil',purpose:'Taking part in learning',icon:'pencil'},{task:'Using a word',purpose:'Asking, choosing, saying “stop”',icon:'speech'},{task:'Taking a step',purpose:'Reaching somewhere the child wants to go',icon:'steps'}],
 thesis:'Your child’s life decides the work. PinnacleAI® starts there.',
 implementation:'AbilityScore® informs the starting picture. Goals identify what to work on. The child-specific Personal Development Kernel connects that picture with the programme and feedback. People practise, observe and review; the next decision returns to what matters in the child’s life.',
 sourceBoundary:'The 160-year framing is the monograph’s historical thesis. It is not a finding that every provider failed throughout that period. WHO–UNICEF documents care gaps; it does not endorse PinnacleAI® or establish comparative superiority.'
};
const glyphs={pencil:'<path d="m4 16 12-12 4 4L8 20H4zM13 7l4 4M4 20l4-1"/>',speech:'<path d="M4 4h16v12H9l-5 4zM8 8h8M8 12h5"/>',steps:'<path d="M3 20h6v-5h6v-5h6M5 6l3-3 3 3M8 3v8"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5z"/>'};
const icon=n=>'<svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+glyphs[n]+'</svg>';
const lane=(items,kind)=>'<ol class="thesis-path '+kind+'">'+items.map((s,i)=>'<li><span class="thesis-step" aria-hidden="true">'+(i+1)+'</span><span>'+e(s)+'</span></li>').join('')+'</ol>';
const share='PinnacleAI® Paradigm Shift: the outcome belongs at the beginning. Start with the child’s self-sufficient, mainstream life, then choose the abilities, goals, people and practice that serve it. Read the historical argument, the supplied example and the sources.\n\n'+base+'evidence/pinnacle-paradigm-shift.html#change-the-starting-point';
const markup=`<section class="thesis-story wrap" id="overview" aria-labelledby="thesis-title">
<header class="thesis-opening"><p class="eyebrow">The PinnacleAI® paradigm shift</p><h2 id="thesis-title">The outcome belongs<br><em>at the beginning.</em></h2><p>More assessments. More techniques. More sessions.<br><strong>What life are we building for the child?</strong></p></header>
<section class="thesis-history" id="history-and-purpose" aria-labelledby="history-purpose-title">
 <div class="thesis-years"><strong>160<span>years</span></strong><p>The historical challenge in<br>Pinnacle’s AbilityScore® monograph</p><a href="${data.history.url}" target="_blank" rel="noopener">Read the monograph ↗</a></div>
 <div class="thesis-history-copy"><p class="eyebrow">The parts and the whole</p><h3 id="history-purpose-title">The life question cannot<br>be left until later.</h3><p>${e(data.history.thesis)}</p><p>${e(data.history.gap)}</p><p class="thesis-family-question">A family can carry reports from every appointment—and still need an answer to: <strong>“What will this help my child do?”</strong></p></div>
 <div class="thesis-external"><span>2023 · WHO &amp; UNICEF</span><p>Unmet needs. Fragmented systems. Waiting lists. Exclusion. The global report calls for people-centred services and support for caregivers.</p><a href="${data.independentContext.url}" target="_blank" rel="noopener">Read the independent context ↗</a></div>
 <details class="thesis-source-note"><summary>Follow the historical sources: 2001 → 2006 → 2023 <span aria-hidden="true">+</span></summary><ol class="thesis-milestones">${data.milestones.map(x=>`<li><strong>${x.year} · ${e(x.title)}</strong><p>${e(x.text)}</p><a href="${e(x.url)}" target="_blank" rel="noopener">Read the original source ↗</a></li>`).join('')}</ol><p>${e(data.sourceBoundary)}</p><p>The critique concerns the order of decisions: whether techniques are selected before their contribution to the child’s life is made explicit. Specialist expertise is essential to doing that work well.</p></details>
</section>
<section class="thesis-reversal" id="change-the-starting-point" aria-labelledby="reversal-title"><header><p class="eyebrow">Change where the work begins</p><h3 id="reversal-title">Life determines the work.<br><em>The work must answer to life.</em></h3></header>
 <div class="thesis-lanes"><div class="thesis-lane method-lane"><span class="thesis-lane-label">When the method comes first</span><h4>“Which therapy?”</h4>${lane(data.methodFirst,'method-path')}<p>The life question arrives at the end.</p></div><div class="thesis-lane life-lane"><span class="thesis-lane-label">PinnacleAI® · life first</span><h4>“What does this child<br>need for life?”</h4>${lane(data.lifeFirst,'life-path')}<p>The life question governs every step.</p></div></div>
 <p class="thesis-comparison-note">${e(data.comparisonScope)}</p>
 <p class="thesis-statement">${e(data.thesis)}</p>
</section>
<div class="thesis-moon"><img src="assets/moon-600.webp" width="600" height="400" loading="lazy" decoding="async" alt="A rocket follows a luminous route toward the Moon."><div><p class="eyebrow">A simple way to see the difference</p><h3>The Moon was the mission.<br><em>The rocket was the means.</em></h3><p>The destination determined the engineering, the people and the preparation. At Pinnacle, <strong>${e(data.purpose.toLowerCase().replace(/\.$/,''))}</strong> is the purpose that guides the work.</p></div></div>
<section class="thesis-transfer" id="from-task-to-life" aria-labelledby="transfer-title"><h3 id="transfer-title">A skill matters through<br>what it makes possible.</h3><div class="thesis-examples">${data.examples.map(x=>`<div>${icon(x.icon)}<span>${e(x.task)}</span><span class="thesis-arrow" aria-hidden="true">↓</span><strong>${e(x.purpose)}</strong></div>`).join('')}</div><p>From the first conversation through review, school readiness and continuing support, the question returns: <strong>what is becoming possible in this child’s life?</strong></p></section>
<div class="thesis-bridge"><div><p class="eyebrow">Now see the philosophy inside the work</p><h3>“Help.” “More.” “Stop.”<br><em>A child’s voice becomes the goal.</em></h3><p>Follow one life ability into a measurable goal, the activities selected for it, family practice and what the team would record for review.</p></div><div class="thesis-actions"><a class="button primary" href="#documented-example">See how the goal shapes the session ${icon('arrow')}</a><a class="thesis-share" href="https://wa.me/?text=${e(encodeURIComponent(share))}" target="_blank" rel="noopener">Share the paradigm shift on WhatsApp ↗</a></div></div>
</section>`;
const styles=`
.thesis-story{padding-block:42px 14px;color:var(--navy)}.thesis-opening{max-width:850px;padding-bottom:30px}.thesis-opening h2{font-size:clamp(36px,4.8vw,64px);line-height:1.02;letter-spacing:-.035em;margin:15px 0 23px}.thesis-opening>p:last-child{font-size:22px;line-height:1.55;color:var(--muted)}.thesis-opening>p:last-child strong{color:var(--navy)}
.thesis-history{display:grid;grid-template-columns:260px minmax(0,1fr);gap:27px 38px;padding:34px;border:1px solid #dddde7;border-radius:22px;background:#fff}.thesis-years{padding:5px 0}.thesis-years>strong{font-size:105px;line-height:.95;letter-spacing:-.07em;color:var(--purple);display:block;font-weight:740}.thesis-years>strong span{display:block;font-size:32px;letter-spacing:-.02em;line-height:1.2;margin-top:7px}.thesis-years p{font-size:14px;line-height:1.5;color:var(--muted);margin-top:22px}.thesis-history a{display:inline-flex;align-items:center;min-height:44px;font-size:14px;font-weight:650;color:var(--teal);text-underline-offset:4px}.thesis-history-copy .eyebrow{color:var(--red);font-size:11px}.thesis-history h3{font-size:34px;line-height:1.1;margin:11px 0 20px}.thesis-history-copy>p:not(.eyebrow){font-size:17px;line-height:1.65;color:var(--muted);margin:0 0 17px}.thesis-history-copy .thesis-family-question{border-left:3px solid #dc5976;padding:14px 0 14px 20px;margin-top:23px!important;color:var(--navy)!important}.thesis-external{grid-column:1/-1;display:grid;grid-template-columns:210px minmax(0,1fr);gap:8px 25px;border-top:1px solid var(--line);padding-top:23px}.thesis-external>span{font-size:12px;font-weight:730;color:var(--purple);letter-spacing:.04em}.thesis-external p{margin:0;font-size:16px;line-height:1.55;color:var(--muted)}.thesis-external a{grid-column:2}.thesis-source-note{grid-column:1/-1;border-top:1px solid var(--line);font-size:13px;line-height:1.65;color:var(--muted)}.thesis-source-note summary{cursor:pointer;min-height:46px;display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:13px;font-weight:650;color:var(--teal)}
.thesis-reversal{padding-top:43px}.thesis-reversal>header{max-width:800px}.thesis-reversal h3,.thesis-transfer>h3{font-size:41px;line-height:1.1;margin:13px 0 25px;letter-spacing:-.025em}.thesis-lanes{display:grid;grid-template-columns:1fr 1fr;gap:22px}.thesis-lane{padding:27px;border:1px solid #dfd9e1;border-radius:19px;background:#fff;min-width:0}.life-lane{border:2px solid #86bec0;background:#f5fbfa}.thesis-lane-label{display:block;font-size:11px;line-height:1.5;font-weight:730;text-transform:uppercase;letter-spacing:.07em;color:#a12c51}.life-lane .thesis-lane-label{color:var(--teal)}.thesis-lane h4{font-size:26px;line-height:1.18;margin:15px 0 23px;min-height:62px}.thesis-path{list-style:none;padding:0;margin:0}.thesis-path li{position:relative;display:flex;align-items:center;gap:15px;min-height:82px;padding-block:10px;font-size:17px;line-height:1.45}.thesis-path li:not(:last-child):after{content:'';position:absolute;left:18px;top:calc(50% + 20px);height:calc(100% - 39px);border-left:1px dashed #c7c0cc}.thesis-step{display:grid;place-items:center;width:37px;height:37px;flex:0 0 37px;border-radius:50%;border:1px solid #ded4dc;color:#99516b;font-size:12px;font-weight:700;background:#fff}.life-path .thesis-step{border-color:#84bfc1;color:var(--teal)}.life-path li:first-child{font-weight:700;color:var(--teal)}.thesis-lane>p{border-top:1px solid #d7e3e4;padding-top:17px;margin:20px 0 0;font-size:17px;font-weight:650}.life-lane>p{color:var(--teal)}.thesis-comparison-note{font-size:12px;line-height:1.6;color:var(--muted);margin:15px 0 0}.thesis-statement{font-size:27px;line-height:1.3;color:var(--navy);font-weight:730;letter-spacing:-.015em;margin:25px 0 0}
.thesis-moon{display:grid;grid-template-columns:1fr 1.15fr;gap:38px;align-items:center;padding-block:34px}.thesis-moon img{display:block;width:100%;height:auto;max-height:285px;object-fit:contain}.thesis-moon h3{font-size:34px;line-height:1.12;margin:14px 0 18px}.thesis-moon p:last-child{font-size:18px;line-height:1.65;color:var(--muted)}.thesis-transfer{padding-top:25px;border-top:1px solid var(--line)}.thesis-examples{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:17px}.thesis-examples>div{display:flex;flex-direction:column;gap:13px;border:1px solid var(--line);border-radius:15px;padding:23px;color:var(--teal);background:#fff}.thesis-examples>div>span{font-size:15px;color:var(--muted)}.thesis-examples .thesis-arrow{font-size:19px;line-height:1;color:var(--purple)}.thesis-examples strong{font-size:22px;line-height:1.25;color:var(--navy)}.thesis-transfer>p{font-size:18px;line-height:1.6;color:var(--muted);max-width:880px;margin-top:23px}.thesis-bridge{display:grid;grid-template-columns:1.3fr 1fr;gap:30px;align-items:center;padding:29px;margin-top:34px;border-block:1px solid var(--line);background:#f6faf9;border-radius:17px}.thesis-bridge h3{font-size:31px;line-height:1.15;margin:14px 0 20px}.thesis-bridge p:last-child{font-size:17px;line-height:1.6;color:var(--muted);margin:0}.thesis-actions{display:flex;flex-direction:column;align-items:flex-start;gap:14px}.thesis-actions .button{font-size:15px;line-height:1.45;text-align:left}.thesis-share{font-size:13px;min-height:44px;display:inline-flex;align-items:center;color:var(--teal);text-underline-offset:3px}.thesis-story a:focus-visible,.thesis-story summary:focus-visible{outline:3px solid var(--purple);outline-offset:4px}
@media(max-width:760px){.thesis-story{padding-top:28px}.thesis-opening{padding-bottom:15px}.thesis-opening h2{font-size:40px}.thesis-opening>p:last-child{font-size:19px}.thesis-history{grid-template-columns:1fr;padding:23px 19px;gap:22px;border-radius:17px}.thesis-years>strong{font-size:84px;display:flex;align-items:baseline;gap:13px}.thesis-years>strong span{font-size:29px;display:inline;margin:0}.thesis-years p{font-size:13px;margin:15px 0 0}.thesis-history h3{font-size:29px}.thesis-history-copy>p:not(.eyebrow){font-size:16px;line-height:1.6}.thesis-history-copy .thesis-family-question{padding-left:15px}.thesis-external{grid-template-columns:1fr;gap:10px}.thesis-external a{grid-column:auto}.thesis-external p{font-size:15px}.thesis-reversal{padding-top:31px}.thesis-reversal h3,.thesis-transfer>h3{font-size:32px}.thesis-lanes{grid-template-columns:1fr;gap:17px}.thesis-lane{padding:22px 19px;border-radius:15px}.thesis-lane h4{font-size:26px;min-height:0;margin-bottom:16px}.thesis-path li{font-size:16px;min-height:75px;gap:13px}.thesis-lane>p{font-size:16px}.thesis-statement{font-size:25px}.thesis-moon{grid-template-columns:1fr;gap:8px;padding-block:26px}.thesis-moon img{max-height:200px}.thesis-moon h3{font-size:29px}.thesis-moon p:last-child{font-size:17px}.thesis-examples{grid-template-columns:1fr;gap:12px}.thesis-examples>div{display:grid;grid-template-columns:29px 1fr;gap:8px 13px;padding:18px}.thesis-examples svg{grid-row:1/4}.thesis-examples strong{font-size:21px;grid-column:2}.thesis-examples .thesis-arrow{grid-column:2;font-size:15px}.thesis-transfer>p{font-size:17px}.thesis-bridge{grid-template-columns:1fr;padding:23px 19px;gap:21px}.thesis-bridge h3{font-size:29px}.thesis-bridge p:last-child{font-size:16px}.thesis-actions{align-items:stretch}.thesis-actions .button{justify-content:center}.thesis-share{justify-content:center;text-align:center}.thesis-source-note summary{font-size:12px}}
@media print{.thesis-story{padding-block:15px}.thesis-history,.thesis-lane,.thesis-examples>div{break-inside:avoid}.thesis-lanes{grid-template-columns:1fr 1fr}.thesis-actions{display:none}.thesis-moon img{max-height:160px}}
`;
const markdown=['## '+data.title,'More assessments. More techniques. More sessions. What life are we building for the child?','### 160 years — Pinnacle’s historical challenge',data.history.title+' — '+data.history.author,data.history.thesis,data.history.gap,'Source: '+data.history.url,'### Independently documented care gaps',data.independentContext.year+' · '+data.independentContext.organization+'\n'+data.independentContext.text+'\nSource: '+data.independentContext.url,...data.milestones.map(x=>x.year+' · '+x.title+'\n'+x.text+'\nSource: '+x.url),data.sourceBoundary,'### Change where the work begins',data.comparisonScope,'When the method comes first:\n'+data.methodFirst.map((x,i)=>(i+1)+'. '+x).join('\n'),'PinnacleAI® — life first:\n'+data.lifeFirst.map((x,i)=>(i+1)+'. '+x).join('\n'),data.thesis,'### The Moon was the mission. The rocket was the means.','The destination determined the engineering, the people and the preparation. At Pinnacle, '+data.purpose.toLowerCase()+' That purpose guides the work.','### A skill matters through what it makes possible',...data.examples.map(x=>x.task+' → '+x.purpose),data.implementation,'### See the philosophy inside the work','“Help.” “More.” “Stop.” A child’s voice becomes the goal. Follow one life ability into a measurable goal, the activities selected for it, family practice and what the team would record for review.'].join('\n\n')+'\n\n';
module.exports={data,markup,styles,markdown};
