const fs=require('node:fs'),path=require('node:path');
const root=__dirname,data=JSON.parse(fs.readFileSync(path.join(root,'story.json'),'utf8'));
const {cards,acts}=data,F=data.finale,base=data.url;const storyUrl='https://www.pinnacleblooms.org/verify/evidence/pinnacle-paradigm-shift.html';
const decision=require('./decision-story.cjs');
const foundation=require('./institution-foundation.cjs');
const documented=require('./documented-example.cjs');
const goalExample=require('./goal-session-example.cjs');
const thesis=require('./paradigm-thesis.cjs');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'),'utf8'));
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const line=s=>e(s).replace(/\n/g,'<br>');
const icon=(name)=>`<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${({arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',phone:'<path d="M6 3h4l2 5-3 2c1 3 2 4 5 5l2-3 5 2v4c0 2-2 3-4 2C8 18 3 13 3 6c0-2 1-3 3-3z"/>',report:'<path d="M6 3h9l4 4v14H6zM14 3v5h5M9 12h7m-7 4h7"/>',shield:'<path d="M12 3l8 4v6c0 4-5 7-8 8-3-1-8-4-8-8V7zM8 12l3 3 5-6"/>',people:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-5c0-6 12-6 12 0v5M16 4c5 0 5 6 1 6m1 3c4 0 4 4 4 7"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',spark:'<path d="M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z"/>',loop:'<path d="M20 10a8 8 0 0 0-14-4L3 9m0-6v6h6m-5 5a8 8 0 0 0 14 4l3-3m0 6v-6h-6"/>',check:'<path d="M5 12l4 5L20 5"/>'})[name]||'<circle cx="12" cy="12" r="8"/>'}</svg>`;
function image(name,alt,priority=false,extra=''){
 const a=manifest[name+'-1200'],b=manifest[name+'-600'];
 return `<img class="scene ${extra}" src="assets/${name}-600.webp" srcset="assets/${name}-600.webp ${b.width}w, assets/${name}-1200.webp ${a.width}w" sizes="(max-width:760px) 94vw, 560px" width="${a.width}" height="${a.height}" alt="${e(alt)}" loading="${priority?'eager':'lazy'}" ${priority?'fetchpriority="high"':''} decoding="async">`;
}
const header=()=>'<img class="brand-header" src="assets/brand-header-600.webp" srcset="assets/brand-header-600.webp 600w, assets/brand-header-1200.webp 1200w" sizes="(max-width:760px) 94vw, 660px" width="1727" height="243" alt="Pinnacle Blooms Network supplied brand header" decoding="async">';
const cta=(obj,cls='button')=>`<a class="${cls}" href="${e(obj.href)}">${icon(obj.href.startsWith('tel:')?'phone':obj.href.startsWith('mailto:')?'people':'report')}<span>${e(obj.label)}</span></a>`;
function share(c){return `${data.title}\n${c.title.replace(/\n/g,' ')}\n\n${c.pinnacle}\n\n${data.purpose}\n\n${storyUrl}#${c.id}`;}
const sourceLinks=c=>c.sources.map(([label,url])=>`<a href="${e(url)}" target="_blank" rel="noopener">${e(label)} ↗</a>`).join('');
const note=(text)=>`<p class="caption">${text}</p>`;
const chain=(items,cls='')=>`<ol class="chain ${cls}">${items.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${e(x)}</strong></li>`).join('')}</ol>`;
function visual(c){switch(c.number){
case 2:return `<div class="thesis"><span class="eyebrow">The historical challenge</span><strong>160 years.</strong><p>“Without a Unified Metric.”</p><span>Pinnacle’s AbilityScore® monograph</span><a href="https://doi.org/10.5281/zenodo.19482123" target="_blank" rel="noopener">Read the research argument ↗</a></div>`;
case 3:return image('car','Illustrated comparison: separate automotive parts beside a complete family car.');
case 4:return image('moon','A rocket and its instruments follow a path toward the Moon, illustrating a mission that determines the means.');
case 5:return `<div class="metrics"><div><b>2.7B+</b><span>Structured developmental records</span></div><div><b>31M+</b><span>Recorded services</span></div><div><b>7.9 lakh+</b><span>Beneficiary / family registrations</span></div></div>${note('SRS 4400 factual findings · July 2026 cutoff · different counting units. <a href="'+base+'evidence/assurance-map.html">Read the definitions and report scope ↗</a>')}`;
case 6:return `<div class="framework"><div><b>17</b><span>Developmental domains</span></div><span class="flow-arrow">→</span><div><b>79</b><span>Abilities</span></div><span class="flow-arrow">→</span><div><b>349</b><span>Skills</span></div></div>${note('Pinnacle’s developmental framework. Discuss the assessment and interpretation with the team.')}${image('assessment','Illustrative scene of a parent discussing a developmental assessment.')}`;
case 7:return `<div class="report-visual">${image('report-cover','Title-only cover of the supplied Mainstream Readiness Index report.')}<div><strong>One AbilityScore®.<br>Seven readiness views.</strong><p>See a real report format. Ask how its findings inform your child’s priorities.</p><a href="${base}#report-explorer" target="_blank" rel="noopener">Open the report explorer ↗</a></div></div>${note('Supplied report cover; child-specific details are excluded. The cover design is a presentation version.')}`;
case 8:return `<div class="kernel"><span class="kernel-top">Pinnacle’s wider knowledge</span><span class="kernel-line">↓</span><div class="kernel-core">${icon('people')}<b>Your child’s<br>Personal Development Kernel</b></div><div class="kernel-inputs"><span>Abilities</span><span>Goals</span><span>Context</span><span>Feedback</span></div><span class="kernel-line">↓</span><strong>Child-specific recommendations<br>with human review</strong></div>`;
case 9:return chain(['A meaningful life priority','The ability or skill it needs','A goal you can understand','An observable way to review it']);
case 10:return `<div class="feedback-demo"><p class="eyebrow">Explore the principle</p><h4>A proposed goal needs a better fit.</h4><p>What would you want the team to understand?</p><div class="feedback-choices js-only"><button type="button" data-feedback="difficulty" aria-pressed="false">The difficulty</button><button type="button" data-feedback="engagement" aria-pressed="false">My child’s engagement</button><button type="button" data-feedback="purpose" aria-pressed="false">Its life purpose</button></div><div class="feedback-response" role="status"><strong>Your reason belongs in the review.</strong><p>Discuss the concern, reconsider the proposed goal and retain the reason in the child’s record.</p></div>${note('Illustrative workflow, not a live assessment or a product screenshot. Exact rating and replacement rules are in the source notes.')}</div>`;
case 11:return `<div class="ahead"><b>4 days</b><span>ahead to see the proposed programme</span></div>${chain(['Understand the goal','See the selected activity','Prepare the support','Practise and give feedback'])}${note('Advance programme delivery described in Pinnacle’s methodology. See source notes for programme-count versions.')}`;
case 13:return `<div class="feedback-loop">${chain(['Observe the experience','Rate and explain','Bring feedback into the Kernel','Review the next selection'])}<div class="loop-caption">${icon('loop')}<strong>The child’s response returns to the decision.</strong></div></div>`;
case 14:return `<div class="questions"><span>What are we working toward?</span><span>What will the team observe?</span><span>What does the expectation depend on?</span><span>When will we review it?</span></div>${note('Forecasts inform discussion. Actual observations and individual circumstances guide review.')}`;
case 17:return `<div class="mission-scale"><span>Pinnacle’s ambition</span><strong>900 million</strong><p>children, parents and families</p><small>A mission for reach and empowerment.</small></div><div class="proof-tags"><a href="${base}evidence/records/md5.html">${icon('report')} MD-5 intended users</a><a href="${base}evidence/records/bis.html">${icon('shield')} BIS lifecycle scope</a></div>`;
default:{const names={1:'hero',12:'practice',15:'review',16:'learning',18:'family'};const namesAlt={1:'Illustrative scene of a child and mother being welcomed at school.',12:'Illustrative scene of guided everyday practice.',15:'Illustrative scene of a family reviewing progress with professional support.',16:'Illustrative scene connecting a learning activity with participation.',18:'Illustrative scene of a mother and child learning together.'};return image(names[c.number]||'team',namesAlt[c.number]||'Illustrative scene of people supporting a child’s developmental priorities.');}
}}
function card(c,i){const group=acts.find(a=>a.id===c.act),next=cards[i+1],prev=cards[i-1];return `<article class="chapter" id="${e(c.id)}" data-card="${c.number}" data-act="${e(c.act)}" aria-labelledby="title-${c.number}">
<div class="poster"><div class="poster-header">${header()}<div class="card-brand"><span>PinnacleAI® Paradigm Shift</span><span>${String(c.number).padStart(2,'0')} / 18</span></div></div><p class="eyebrow">${e(group.title.replace(/^\d+ · /,''))}</p><h2 id="title-${c.number}">${line(c.title)}</h2><p class="hook">${e(c.hook)}</p><div class="card-visual visual-${c.number}">${visual(c)}</div><div class="contrast"><section class="before"><h3>${e(c.contrastLabel)}</h3><p>${e(c.contrast)}</p></section><section class="after"><h3>${icon('spark')} PinnacleAI® Paradigm Shift</h3><p>${e(c.pinnacle)}</p></section></div><p class="punch">${e(c.punch)}</p><p class="purpose">${e(data.purpose)}</p><div class="poster-footer"><span>${e(data.tagline)}</span><span>pinnacleblooms.org/verify</span></div></div>
<aside class="reading" aria-label="Details for story ${c.number}"><p class="eyebrow">Understand the difference</p><h3>${e(c.punch)}</h3><p class="reading-lead">${e(c.pinnacle)}</p><details><summary>Read the full story <span>+</span></summary><div class="detail-body">${c.narration.map(p=>`<p>${e(p)}</p>`).join('')}</div></details><details><summary>See how it works <span>+</span></summary><div class="detail-body"><ul>${c.mechanism.map(p=>`<li>${e(p)}</li>`).join('')}</ul></div></details><details><summary>Inspect the evidence <span>+</span></summary><div class="detail-body"><ul>${c.proof.map(p=>`<li>${e(p)}</li>`).join('')}</ul><div class="source-links">${sourceLinks(c)}</div></div></details>
<div class="reader-cta">${cta(F.parentCTA,'button primary')}<a href="${e(F.reportCTA.href)}" class="text-link">See a report example ↗</a></div><details class="share"><summary>Share this part of the story <span>+</span></summary><div class="share-actions"><a href="https://wa.me/?text=${encodeURIComponent(share(c))}" target="_blank" rel="noopener">WhatsApp ↗</a><a href="https://twitter.com/intent/tweet?text=${encodeURIComponent(c.title.replace(/\n/g,' ')+' '+c.punch)}&amp;url=${encodeURIComponent(storyUrl+'#'+c.id)}" target="_blank" rel="noopener">X ↗</a><button type="button" data-copy="${c.number}" class="js-only">Copy story</button><a href="#${e(c.id)}" aria-label="Link to card ${c.number}">Card link</a></div><p class="copy-status" id="copy-status-${c.number}" role="status"></p><details id="copy-fallback-${c.number}"><summary>Text to copy <span>+</span></summary><textarea readonly aria-label="Share text for story ${c.number}">${e(share(c))}</textarea></details></details><div class="chapter-links">${prev?`<a href="#${prev.id}">← Previous</a>`:'<a href="#overview">↑ Overview</a>'}${next?`<a href="#${next.id}">Next: ${c.number+1} / 18 →</a>`:'<a href="#contact">Your next step →</a>'}</div></aside></article>`;}
const chapterLabels=['The shift','Your child','Daily practice','Life & progress'];
const cardHtml=cards.map(card).join('');
const browserData=JSON.stringify(cards.map(c=>({number:c.number,id:c.id,act:c.act,title:c.title,share:share(c)}))).replace(/</g,'\\u003c');
const css=fs.readFileSync(path.join(root,'finale.css'),'utf8')+'\n'+decision.styles+'\n'+foundation.styles+'\n'+documented.styles+'\n'+goalExample.styles+'\n'+thesis.styles+'\n'+fs.readFileSync(path.join(root,'reading-route.css'),'utf8');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="The PinnacleAI® paradigm shift: begin with a child’s self-sufficient, mainstream life, then choose the abilities, goals, practice and review that serve it."><meta name="theme-color" content="#007f87"><title>PinnacleAI® Paradigm Shift — Life is the mission</title><link rel="icon" href="assets/favicon.png"><link rel="preload" href="assets/anek-latin.woff2" as="font" type="font/woff2" crossorigin><style>${css}</style></head><body>
<a class="skip" href="#story">Skip to the full story</a>
<header class="site-header wrap">${header()}<a class="evidence-link" href="${base}" target="_blank" rel="noopener">${icon('shield')} Evidence portal ↗</a></header>
<main>
<section class="hero wrap" id="top"><div class="hero-title"><p class="eyebrow">${e(F.heroEyebrow)}</p><h1>${e(F.heroTitle.split("\n")[0])}<br><em>${e(F.heroTitle.split("\n").slice(1).join(" "))}</em></h1></div><div class="hero-image">${image('hero','Illustrative scene of a child and mother welcomed into school life.',true)}<span class="image-word">A life of possibilities.</span></div><div class="hero-copy"><p class="hero-purpose">${e(F.heroPurpose)}</p><p>${e(F.heroSupport)}</p><div class="actions"><a class="button primary" href="#overview">See the paradigm shift ${icon('arrow')}</a>${cta(F.parentCTA,'button secondary')}</div><p class="small">PinnacleAI® · Non-diagnostic developmental support · Ages 0–12</p></div></section>
<nav class="main-route wrap" aria-label="Choose your reading route"><a href="#overview"><span>01</span> Why the shift</a><a href="#documented-example"><span>02</span> See it in practice</a><a href="#institutional-foundation"><span>03</span> Examine the evidence</a><a href="#complete-story"><span>04</span> The full story</a></nav>
${thesis.markup}
${goalExample.markup}
<details class="report-source-reader wrap" id="report-source-reader"><summary>Also explore a supplied assessment report: one priority, four professional contributions <span aria-hidden="true">+</span></summary>${documented.markup.replace('id="documented-example"','id="documented-report"')}</details>
${foundation.markup}
<details class="optional-reading wrap" id="illustrative-examples"><summary><span><small>Try the principle</small><strong>Three everyday priorities. Five decisions each.</strong><span>Explore the interactive examples at your own pace.</span></span><b>Open examples +</b></summary><div class="optional-inner">${decision.markup}</div></details>
<details class="complete-reading" id="complete-story"><summary class="wrap"><span><small>The full PinnacleAI® story</small><strong>Eighteen parts. All the depth, when you want it.</strong><span>Comparisons, product mechanisms, sources and sharing.</span></span><b>Open the story +</b></summary><section class="story-intro wrap" id="story"><p>Choose a chapter, move one card at a time, or read all eighteen. Open the explanation and evidence wherever you want more detail.</p></section>
<nav class="navigation" aria-label="Story navigation"><div class="wrap"><div class="act-nav">${acts.map((a,i)=>`<a href="#${cards.find(c=>c.act===a.id).id}" data-act-link="${a.id}"><span>0${i+1}</span>${chapterLabels[i]}</a>`).join('')}</div><div class="reader js-only"><button id="previous" aria-label="Previous story card" type="button">←</button><label class="sr-only" for="card-selector">Choose a story card</label><select id="card-selector">${cards.map(c=>`<option value="${c.number}">${String(c.number).padStart(2,'0')} · ${e(c.title.replace(/\n/g,' '))}</option>`).join('')}</select><button id="next" aria-label="Next story card" type="button">→</button><span id="counter" class="counter">1 / 18</span><button id="mode" type="button">Read all 18</button></div><p id="announcement" class="sr-only" role="status"></p></div></nav>
<div class="chapters">${cardHtml}</div></details>
<section class="contact-section wrap" id="contact"><div><p class="eyebrow">For your family</p><h2>${e(F.closingTitle)}</h2><p>${e(F.closingBody)}</p><div class="actions">${cta(F.parentCTA,'button primary')}${cta(F.reportCTA,'button secondary')}</div><a class="phone-number" href="tel:+919100181181">9100 181 181</a><a class="care-mail" href="mailto:care@pinnacleblooms.org">care@pinnacleblooms.org</a></div><div class="institution"><span class="icon-large">${icon('people')}</span><p class="eyebrow">For institutions and partners</p><h3>${e(F.institutionalTitle)}</h3><p>${e(F.institutionalBody)}</p>${cta(F.institutionCTA,'button secondary')}</div></section>
</main><footer class="footer wrap"><p class="signature">${e(data.tagline)}</p><div class="footer-links"><a href="${base}" target="_blank" rel="noopener">Evidence portal ↗</a><a href="PinnacleAI-Paradigm-Shift-Finale.md">Complete manuscript</a><button type="button" id="print-story" class="js-only">Print story cards</button><a href="#top">Back to the beginning ↑</a></div><details><summary>Sources, scope and editorial notes <span>+</span></summary><div class="editorial"><p>This campaign explains Pinnacle’s approach and purpose. Outcomes depend on the individual child and the support they need. Comparisons describe organising approaches, not every provider. The 160-year thesis is attributed to Pinnacle’s monograph.</p><p>People, Moon and car scenes are illustrative artwork. The report cover is a supplied document excerpt. Brand-header marks do not extend the scope of the licences or registrations described in the evidence portal.</p><p>This is the local campaign finale. The public evidence portal remains linked separately. Product-version and evidence decisions are retained below.</p><div class="register">${data.evidenceRegister.map(x=>`<details><summary>${e(x.category)}<span>+</span></summary><p><strong>${e(x.detail)}</strong></p><p>${e(x.decision)}</p></details>`).join('')}</div></div></details></footer>
<script>(()=>{'use strict';document.documentElement.classList.add('js');const cards=${browserData},chapters=[...document.querySelectorAll('.chapter')],selector=document.getElementById('card-selector'),mode=document.getElementById('mode'),navigation=document.querySelector('.navigation');let selected=Math.max(0,cards.findIndex(c=>'#'+c.id===location.hash)),focus=true,pending=false;
function revealTarget(hash){let target;try{target=document.getElementById(decodeURIComponent(hash.replace(/^#/,'')))}catch{return null}if(!target)return null;for(let el=target;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;return target;}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>revealTarget(a.getAttribute('href'))));
document.querySelectorAll('#illustrative-examples,#complete-story').forEach(d=>d.addEventListener('toggle',()=>{const b=d.querySelector(':scope > summary > b');const noun=d.id==='complete-story'?'the story':'examples';if(b)b.textContent=(d.open?'Close ':'Open ')+noun+(d.open?' −':' +')}));
function labels(){const c=cards[selected];selector.value=String(c.number);document.getElementById('counter').textContent=c.number+' / '+cards.length;document.getElementById('previous').disabled=selected===0;document.getElementById('next').disabled=selected===cards.length-1;document.querySelectorAll('[data-act-link]').forEach(a=>a.dataset.actLink===c.act?a.setAttribute('aria-current','step'):a.removeAttribute('aria-current'));}
function refresh(scroll){chapters.forEach((c,i)=>c.hidden=focus&&i!==selected);labels();mode.textContent=focus?'Read all 18':'One card at a time';document.getElementById('announcement').textContent='Story '+cards[selected].number+' of 18: '+cards[selected].title.replace(/\\n/g,' ');if(scroll)chapters[selected].scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}
function choose(i,hash=true){selected=Math.max(0,Math.min(cards.length-1,i));revealTarget('#'+cards[selected].id);if(hash)history.replaceState(null,'','#'+cards[selected].id);refresh(true);}
document.querySelectorAll('a[href^="#"]').forEach(a=>{const i=cards.findIndex(c=>'#'+c.id===a.getAttribute('href'));if(i>=0)a.addEventListener('click',ev=>{ev.preventDefault();choose(i)});});document.getElementById('previous').addEventListener('click',()=>choose(selected-1));document.getElementById('next').addEventListener('click',()=>choose(selected+1));selector.addEventListener('change',()=>choose(cards.findIndex(c=>String(c.number)===selector.value)));mode.addEventListener('click',()=>{focus=!focus;refresh(true)});addEventListener('hashchange',()=>{const i=cards.findIndex(c=>'#'+c.id===location.hash);if(i>=0)choose(i,false);else{const t=revealTarget(location.hash);if(t)requestAnimationFrame(()=>t.scrollIntoView({block:'start'}))}});
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const c=cards.find(c=>String(c.number)===b.dataset.copy),status=document.getElementById('copy-status-'+c.number);try{await navigator.clipboard.writeText(c.share);status.textContent='Story copied. Ready to share.';}catch{const f=document.getElementById('copy-fallback-'+c.number);f.open=true;f.querySelector('textarea').select();status.textContent='Select and copy the text below.';}}));
const responses={difficulty:['Explain what felt too easy or too difficult.','The concern can inform a discussion about adjusting or replacing the proposed goal, with the reason retained for review.'],engagement:['Describe what helped your child engage.','Context and preferences can inform a discussion about the activity and support. Engagement and clinical effectiveness are different questions.'],purpose:['Ask what the goal makes possible in life.','Trace the goal back to an ability and the life priority it is intended to support. Ask the team to explain the relationship.']};document.querySelectorAll('[data-feedback]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-feedback]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const [title,body]=responses[b.dataset.feedback],out=document.querySelector('.feedback-response');out.querySelector('strong').textContent=title;out.querySelector('p').textContent=body;}));
let printOpenState=null;addEventListener('beforeprint',()=>{const story=document.getElementById('complete-story');printOpenState=story.open;story.open=true});addEventListener('afterprint',()=>{if(printOpenState!==null)document.getElementById('complete-story').open=printOpenState;printOpenState=null});document.getElementById('print-story').addEventListener('click',()=>window.print());addEventListener('scroll',()=>{if(focus||pending||!document.getElementById('complete-story').open)return;pending=true;requestAnimationFrame(()=>{pending=false;let candidate=0;chapters.forEach((c,i)=>{if(c.getBoundingClientRect().top<navigation.offsetHeight+35)candidate=i});if(candidate!==selected){selected=candidate;labels()}})},{passive:true});if('ResizeObserver'in window)new ResizeObserver(()=>document.documentElement.style.scrollPaddingTop=(navigation.offsetHeight+16)+'px').observe(navigation);refresh(false);const initial=revealTarget(location.hash);if(cards.some(c=>'#'+c.id===location.hash))requestAnimationFrame(()=>refresh(true));else if(initial)requestAnimationFrame(()=>initial.scrollIntoView({block:'start'}));})();${decision.script}${goalExample.script}</script></body></html>`;
if(cards.length!==18)throw new Error('Expected 18 story cards');
for(const c of cards){for(const f of ['title','hook','pinnacle','contrast','punch'])if(!html.includes(line(c[f])))throw new Error('Missing '+c.number+' '+f);for(const f of ['narration','mechanism','proof'])for(const text of c[f])if(!html.includes(e(text)))throw new Error('Missing detail '+c.number+' '+f);}
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);if(new Set(ids).size!==ids.length)throw new Error('Duplicate IDs');
new Function(html.match(/<script>([\s\S]*?)<\/script>/)[1]);

module.exports={html,data};
